"""Generated immutable builtin declarations for the btrc LSP.

Auto-generated from stdlib .btrc files by tools/compiler_codegen/builtins.py.
DO NOT EDIT BY HAND — edit the stdlib source or the generator instead.

"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class BuiltinMemberSpec:
    """Generated schema for one builtin field or method."""

    name: str
    return_type: str
    kind: str  # "field" or "method"
    params: tuple[tuple[str, str], ...] = ()
    doc: str = ""


# ---------------------------------------------------------------------------
# Built-in type member tables
# ---------------------------------------------------------------------------

# String methods are language intrinsics (not defined in any .btrc file)
STRING_MEMBERS: tuple[BuiltinMemberSpec, ...] = (
    BuiltinMemberSpec("len", "int", "field", (), "Length of the string (bytes)"),
    BuiltinMemberSpec("charAt", "char", "method", (("int", "index"),), "Character at index"),
    BuiltinMemberSpec("trim", "string", "method", (), "Remove leading/trailing whitespace"),
    BuiltinMemberSpec("lstrip", "string", "method", (), "Remove leading whitespace"),
    BuiltinMemberSpec("rstrip", "string", "method", (), "Remove trailing whitespace"),
    BuiltinMemberSpec("toUpper", "string", "method", (), "Convert to uppercase"),
    BuiltinMemberSpec("toLower", "string", "method", (), "Convert to lowercase"),
    BuiltinMemberSpec("contains", "bool", "method", (("string", "sub"),), "Check if contains substring"),
    BuiltinMemberSpec("startsWith", "bool", "method", (("string", "prefix"),), "Check prefix"),
    BuiltinMemberSpec("endsWith", "bool", "method", (("string", "suffix"),), "Check suffix"),
    BuiltinMemberSpec("indexOf", "int", "method", (("string", "sub"),), "Index of first occurrence"),
    BuiltinMemberSpec("lastIndexOf", "int", "method", (("string", "sub"),), "Index of last occurrence"),
    BuiltinMemberSpec("substring", "string", "method", (("int", "start"), ("int", "end"),), "Extract substring"),
    BuiltinMemberSpec("equals", "bool", "method", (("string", "other"),), "Compare strings"),
    BuiltinMemberSpec("split", "Vector<string>", "method", (("string", "delim"),), "Split into list"),
    BuiltinMemberSpec("replace", "string", "method", (("string", "old"), ("string", "replacement"),), "Replace occurrences"),
    BuiltinMemberSpec("repeat", "string", "method", (("int", "count"),), "Repeat N times"),
    BuiltinMemberSpec("count", "int", "method", (("string", "sub"),), "Count non-overlapping occurrences"),
    BuiltinMemberSpec("find", "int", "method", (("string", "sub"), ("int", "start"),), "Find from start index"),
    BuiltinMemberSpec("capitalize", "string", "method", (), "Uppercase first char"),
    BuiltinMemberSpec("title", "string", "method", (), "Capitalize each word"),
    BuiltinMemberSpec("swapCase", "string", "method", (), "Swap upper/lower case"),
    BuiltinMemberSpec("padLeft", "string", "method", (("int", "width"), ("char", "fill"),), "Left-pad"),
    BuiltinMemberSpec("padRight", "string", "method", (("int", "width"), ("char", "fill"),), "Right-pad"),
    BuiltinMemberSpec("center", "string", "method", (("int", "width"), ("char", "fill"),), "Center with padding"),
    BuiltinMemberSpec("charLen", "int", "method", (), "UTF-8 character count"),
    BuiltinMemberSpec("byteLen", "int", "method", (), "Byte length"),
    BuiltinMemberSpec("isDigitStr", "bool", "method", (), "All chars are digits"),
    BuiltinMemberSpec("isAlphaStr", "bool", "method", (), "All chars are alphabetic"),
    BuiltinMemberSpec("isBlank", "bool", "method", (), "Empty or all whitespace"),
    BuiltinMemberSpec("isAlnum", "bool", "method", (), "All chars are alphanumeric"),
    BuiltinMemberSpec("isUpper", "bool", "method", (), "All chars are uppercase"),
    BuiltinMemberSpec("isLower", "bool", "method", (), "All chars are lowercase"),
    BuiltinMemberSpec("reverse", "string", "method", (), "Reverse the string"),
    BuiltinMemberSpec("isEmpty", "bool", "method", (), "True if string is empty"),
    BuiltinMemberSpec("removePrefix", "string", "method", (("string", "prefix"),), "Remove prefix if present"),
    BuiltinMemberSpec("removeSuffix", "string", "method", (("string", "suffix"),), "Remove suffix if present"),
    BuiltinMemberSpec("toInt", "int", "method", (), "Parse as integer"),
    BuiltinMemberSpec("toFloat", "float", "method", (), "Parse as float"),
    BuiltinMemberSpec("toDouble", "double", "method", (), "Parse as double"),
    BuiltinMemberSpec("toLong", "long", "method", (), "Parse as long"),
    BuiltinMemberSpec("toBool", "bool", "method", (), "Parse as bool (false for empty, \"false\", \"0\")"),
    BuiltinMemberSpec("zfill", "string", "method", (("int", "width"),), "Left-pad with zeros (preserves sign)"),
)

# Atomic is a compiler intrinsic (not defined in stdlib source)
ATOMIC_MEMBERS: tuple[BuiltinMemberSpec, ...] = (
    BuiltinMemberSpec("init", "void", "method", (("T", "value"),), "Initialize stable atomic storage"),
    BuiltinMemberSpec("load", "T", "method", (("MemoryOrder", "order"),), "Load with explicit C11 ordering"),
    BuiltinMemberSpec("store", "void", "method", (("T", "value"), ("MemoryOrder", "order"),), "Store with explicit C11 ordering"),
    BuiltinMemberSpec("exchange", "T", "method", (("T", "value"), ("MemoryOrder", "order"),), "Exchange with explicit C11 ordering"),
    BuiltinMemberSpec("fetchAdd", "T", "method", (("T", "value"), ("MemoryOrder", "order"),), "Atomically add and return the previous value"),
    BuiltinMemberSpec("fetchSub", "T", "method", (("T", "value"), ("MemoryOrder", "order"),), "Atomically subtract and return the previous value"),
    BuiltinMemberSpec("fetchAnd", "T", "method", (("T", "value"), ("MemoryOrder", "order"),), "Atomically AND and return the previous value"),
    BuiltinMemberSpec("fetchOr", "T", "method", (("T", "value"), ("MemoryOrder", "order"),), "Atomically OR and return the previous value"),
    BuiltinMemberSpec("fetchXor", "T", "method", (("T", "value"), ("MemoryOrder", "order"),), "Atomically XOR and return the previous value"),
    BuiltinMemberSpec("compareExchangeStrong", "bool", "method", (("T*", "expected"), ("T", "desired"), ("MemoryOrder", "successOrder"), ("MemoryOrder", "failureOrder"),), "Strong compare-exchange with exact C11 ordering"),
)

# Span is a compiler intrinsic (not defined in stdlib source)
SPAN_MEMBERS: tuple[BuiltinMemberSpec, ...] = (
    BuiltinMemberSpec("length", "size_t", "method", (), "Borrowed element count"),
    BuiltinMemberSpec("isEmpty", "bool", "method", (), "Whether the borrowed extent is empty"),
    BuiltinMemberSpec("isValid", "bool", "method", (), "Whether pointer and extent form a valid view"),
    BuiltinMemberSpec("tryGet", "bool", "method", (("size_t", "index"), ("T*", "output"),), "Copy an in-range element without changing output on failure"),
    BuiltinMemberSpec("trySet", "bool", "method", (("size_t", "index"), ("T", "value"),), "Replace an in-range element"),
)

# Generated from src/stdlib/array.btrc
ARRAY_MEMBERS: tuple[BuiltinMemberSpec, ...] = (
    BuiltinMemberSpec("len", "int", "field", doc="len"),
    BuiltinMemberSpec("get", "T", "method", (("int", "i"),), "get"),
    BuiltinMemberSpec("set", "void", "method", (("int", "i"), ("T", "val"),), "set"),
    BuiltinMemberSpec("fill", "void", "method", (("T", "val"),), "fill"),
    BuiltinMemberSpec("contains", "bool", "method", (("T", "val"),), "contains"),
    BuiltinMemberSpec("indexOf", "int", "method", (("T", "val"),), "indexOf"),
    BuiltinMemberSpec("swap", "void", "method", (("int", "i"), ("int", "j"),), "swap"),
    BuiltinMemberSpec("reverse", "void", "method", (), "reverse"),
    BuiltinMemberSpec("size", "int", "method", (), "size"),
    BuiltinMemberSpec("isEmpty", "bool", "method", (), "isEmpty"),
    BuiltinMemberSpec("free", "void", "method", (), "free"),
    BuiltinMemberSpec("iterLen", "int", "method", (), "iterLen"),
    BuiltinMemberSpec("iterGet", "T", "method", (("int", "i"),), "iterGet"),
)

# Generated from src/stdlib/ownedclosure.btrc
OWNEDCLOSURE_MEMBERS: tuple[BuiltinMemberSpec, ...] = (
    BuiltinMemberSpec("invokePointer", "Invoke", "method", (), "invokePointer"),
    BuiltinMemberSpec("context", "void*", "method", (), "context"),
    BuiltinMemberSpec("isOpen", "bool", "method", (), "isOpen"),
    BuiltinMemberSpec("close", "bool", "method", (), "close"),
)

# Generated from src/stdlib/callbackregistration.btrc
CALLBACKREGISTRATION_MEMBERS: tuple[BuiltinMemberSpec, ...] = (
    BuiltinMemberSpec("isOpen", "bool", "method", (), "isOpen"),
    BuiltinMemberSpec("close", "bool", "method", (), "close"),
)

# Generated from src/stdlib/listnode.btrc
LISTNODE_MEMBERS: tuple[BuiltinMemberSpec, ...] = (
    BuiltinMemberSpec("value", "T", "field", doc="value"),
    BuiltinMemberSpec("next", "ListNode<T>", "field", doc="next"),
    BuiltinMemberSpec("copiedValue", "T", "method", (), "copiedValue"),
)

# Generated from src/stdlib/list.btrc
LIST_MEMBERS: tuple[BuiltinMemberSpec, ...] = (
    BuiltinMemberSpec("head", "ListNode<T>", "field", doc="head"),
    BuiltinMemberSpec("tail", "ListNode<T>", "field", doc="tail"),
    BuiltinMemberSpec("len", "int", "field", doc="len"),
    BuiltinMemberSpec("pushBack", "void", "method", (("T", "val"),), "pushBack"),
    BuiltinMemberSpec("pushFront", "void", "method", (("T", "val"),), "pushFront"),
    BuiltinMemberSpec("push", "void", "method", (("T", "val"),), "push"),
    BuiltinMemberSpec("popBack", "T", "method", (), "popBack"),
    BuiltinMemberSpec("popFront", "T", "method", (), "popFront"),
    BuiltinMemberSpec("pop", "T", "method", (), "pop"),
    BuiltinMemberSpec("front", "T", "method", (), "front"),
    BuiltinMemberSpec("back", "T", "method", (), "back"),
    BuiltinMemberSpec("get", "T", "method", (("int", "idx"),), "get"),
    BuiltinMemberSpec("set", "void", "method", (("int", "idx"), ("T", "val"),), "set"),
    BuiltinMemberSpec("size", "int", "method", (), "size"),
    BuiltinMemberSpec("isEmpty", "bool", "method", (), "isEmpty"),
    BuiltinMemberSpec("contains", "bool", "method", (("T", "val"),), "contains"),
    BuiltinMemberSpec("indexOf", "int", "method", (("T", "val"),), "indexOf"),
    BuiltinMemberSpec("insert", "void", "method", (("int", "idx"), ("T", "val"),), "insert"),
    BuiltinMemberSpec("remove", "void", "method", (("int", "idx"),), "remove"),
    BuiltinMemberSpec("reverse", "void", "method", (), "reverse"),
    BuiltinMemberSpec("clear", "void", "method", (), "clear"),
    BuiltinMemberSpec("free", "void", "method", (), "free"),
    BuiltinMemberSpec("toVector", "Vector<T>", "method", (), "toVector"),
    BuiltinMemberSpec("iterLen", "int", "method", (), "iterLen"),
    BuiltinMemberSpec("iterGet", "T", "method", (("int", "n"),), "iterGet"),
)

# Generated from src/stdlib/map.btrc
MAP_MEMBERS: tuple[BuiltinMemberSpec, ...] = (
    BuiltinMemberSpec("len", "int", "field", doc="len"),
    BuiltinMemberSpec("put", "void", "method", (("K", "key"), ("V", "value"),), "put"),
    BuiltinMemberSpec("get", "V", "method", (("K", "key"),), "get"),
    BuiltinMemberSpec("getOrDefault", "V", "method", (("K", "key"), ("V", "fallback"),), "getOrDefault"),
    BuiltinMemberSpec("has", "bool", "method", (("K", "key"),), "has"),
    BuiltinMemberSpec("contains", "bool", "method", (("K", "key"),), "contains"),
    BuiltinMemberSpec("putIfAbsent", "void", "method", (("K", "key"), ("V", "value"),), "putIfAbsent"),
    BuiltinMemberSpec("free", "void", "method", (), "free"),
    BuiltinMemberSpec("remove", "void", "method", (("K", "key"),), "remove"),
    BuiltinMemberSpec("clear", "void", "method", (), "clear"),
    BuiltinMemberSpec("size", "int", "method", (), "size"),
    BuiltinMemberSpec("isEmpty", "bool", "method", (), "isEmpty"),
    BuiltinMemberSpec("keys", "Vector<K>", "method", (), "keys"),
    BuiltinMemberSpec("values", "Vector<V>", "method", (), "values"),
    BuiltinMemberSpec("containsValue", "bool", "method", (("V", "value"),), "containsValue"),
    BuiltinMemberSpec("set", "void", "method", (("K", "key"), ("V", "value"),), "set"),
    BuiltinMemberSpec("merge", "void", "method", (("Map<K, V>", "other"),), "merge"),
    BuiltinMemberSpec("iterLen", "int", "method", (), "iterLen"),
    BuiltinMemberSpec("iterGet", "K", "method", (("int", "n"),), "iterGet"),
    BuiltinMemberSpec("iterValueAt", "V", "method", (("int", "n"),), "iterValueAt"),
    BuiltinMemberSpec("forEach", "void", "method", (("fn", "callback"),), "Call fn(key, value) for each entry"),
)

# Generated from src/stdlib/result.btrc
RESULT_MEMBERS: tuple[BuiltinMemberSpec, ...] = (
    BuiltinMemberSpec("isOk", "bool", "method", (), "isOk"),
    BuiltinMemberSpec("isErr", "bool", "method", (), "isErr"),
    BuiltinMemberSpec("unwrap", "T", "method", (), "unwrap"),
    BuiltinMemberSpec("unwrapErr", "E", "method", (), "unwrapErr"),
)

# Generated from src/stdlib/set.btrc
SET_MEMBERS: tuple[BuiltinMemberSpec, ...] = (
    BuiltinMemberSpec("len", "int", "field", doc="len"),
    BuiltinMemberSpec("add", "void", "method", (("T", "key"),), "add"),
    BuiltinMemberSpec("contains", "bool", "method", (("T", "key"),), "contains"),
    BuiltinMemberSpec("has", "bool", "method", (("T", "key"),), "has"),
    BuiltinMemberSpec("remove", "void", "method", (("T", "key"),), "remove"),
    BuiltinMemberSpec("free", "void", "method", (), "free"),
    BuiltinMemberSpec("clear", "void", "method", (), "clear"),
    BuiltinMemberSpec("size", "int", "method", (), "size"),
    BuiltinMemberSpec("isEmpty", "bool", "method", (), "isEmpty"),
    BuiltinMemberSpec("unite", "Set<T>", "method", (("Set<T>", "other"),), "unite"),
    BuiltinMemberSpec("intersect", "Set<T>", "method", (("Set<T>", "other"),), "intersect"),
    BuiltinMemberSpec("subtract", "Set<T>", "method", (("Set<T>", "other"),), "subtract"),
    BuiltinMemberSpec("isSubsetOf", "bool", "method", (("Set<T>", "other"),), "isSubsetOf"),
    BuiltinMemberSpec("isSupersetOf", "bool", "method", (("Set<T>", "other"),), "isSupersetOf"),
    BuiltinMemberSpec("symmetricDifference", "Set<T>", "method", (("Set<T>", "other"),), "symmetricDifference"),
    BuiltinMemberSpec("toVector", "Vector<T>", "method", (), "toVector"),
    BuiltinMemberSpec("copy", "Set<T>", "method", (), "copy"),
    BuiltinMemberSpec("filter", "Set<T>", "method", (("__fn_ptr<bool, T>", "pred"),), "filter"),
    BuiltinMemberSpec("any", "bool", "method", (("__fn_ptr<bool, T>", "pred"),), "any"),
    BuiltinMemberSpec("all", "bool", "method", (("__fn_ptr<bool, T>", "pred"),), "all"),
    BuiltinMemberSpec("forEach", "void", "method", (("__fn_ptr<void, T>", "fn"),), "forEach"),
    BuiltinMemberSpec("iterLen", "int", "method", (), "iterLen"),
    BuiltinMemberSpec("iterGet", "T", "method", (("int", "n"),), "iterGet"),
)

# Generated from src/stdlib/spscqueue.btrc
SPSCQUEUE_MEMBERS: tuple[BuiltinMemberSpec, ...] = (
    BuiltinMemberSpec("tryPush", "bool", "method", (("T", "value"),), "tryPush"),
    BuiltinMemberSpec("tryPop", "bool", "method", (("T*", "output"),), "tryPop"),
    BuiltinMemberSpec("close", "void", "method", (), "close"),
)

# Generated from src/stdlib/state.btrc
STATE_MEMBERS: tuple[BuiltinMemberSpec, ...] = (
    BuiltinMemberSpec("value", "T", "field", doc="value"),
    BuiltinMemberSpec("version", "int", "field", doc="version"),
    BuiltinMemberSpec("get", "T", "method", (), "get"),
    BuiltinMemberSpec("set", "State<T>", "method", (("T", "value"),), "set"),
    BuiltinMemberSpec("changedSince", "bool", "method", (("int", "seenVersion"),), "changedSince"),
)

# Generated from src/stdlib/vector.btrc
VECTOR_MEMBERS: tuple[BuiltinMemberSpec, ...] = (
    BuiltinMemberSpec("len", "int", "field", doc="len"),
    BuiltinMemberSpec("push", "void", "method", (("T", "val"),), "push"),
    BuiltinMemberSpec("pop", "T", "method", (), "pop"),
    BuiltinMemberSpec("get", "T", "method", (("int", "i"),), "get"),
    BuiltinMemberSpec("set", "void", "method", (("int", "i"), ("T", "val"),), "set"),
    BuiltinMemberSpec("free", "void", "method", (), "free"),
    BuiltinMemberSpec("remove", "void", "method", (("int", "idx"),), "remove"),
    BuiltinMemberSpec("reverse", "void", "method", (), "reverse"),
    BuiltinMemberSpec("reversed", "Vector<T>", "method", (), "reversed"),
    BuiltinMemberSpec("swap", "void", "method", (("int", "i"), ("int", "j"),), "swap"),
    BuiltinMemberSpec("clear", "void", "method", (), "clear"),
    BuiltinMemberSpec("fill", "void", "method", (("T", "val"),), "fill"),
    BuiltinMemberSpec("size", "int", "method", (), "size"),
    BuiltinMemberSpec("isEmpty", "bool", "method", (), "isEmpty"),
    BuiltinMemberSpec("first", "T", "method", (), "first"),
    BuiltinMemberSpec("last", "T", "method", (), "last"),
    BuiltinMemberSpec("slice", "Vector<T>", "method", (("int", "start"), ("int", "end"),), "slice"),
    BuiltinMemberSpec("take", "Vector<T>", "method", (("int", "n"),), "take"),
    BuiltinMemberSpec("drop", "Vector<T>", "method", (("int", "n"),), "drop"),
    BuiltinMemberSpec("extend", "void", "method", (("Vector<T>", "other"),), "extend"),
    BuiltinMemberSpec("insert", "void", "method", (("int", "idx"), ("T", "val"),), "insert"),
    BuiltinMemberSpec("contains", "bool", "method", (("T", "val"),), "contains"),
    BuiltinMemberSpec("indexOf", "int", "method", (("T", "val"),), "indexOf"),
    BuiltinMemberSpec("lastIndexOf", "int", "method", (("T", "val"),), "lastIndexOf"),
    BuiltinMemberSpec("count", "int", "method", (("T", "val"),), "count"),
    BuiltinMemberSpec("removeAll", "void", "method", (("T", "val"),), "removeAll"),
    BuiltinMemberSpec("distinct", "Vector<T>", "method", (), "distinct"),
    BuiltinMemberSpec("sort", "void", "method", (), "sort"),
    BuiltinMemberSpec("sorted", "Vector<T>", "method", (), "sorted"),
    BuiltinMemberSpec("sortBy", "void", "method", (("__fn_ptr<bool, T, T>", "less"),), "sortBy"),
    BuiltinMemberSpec("sortedBy", "Vector<T>", "method", (("__fn_ptr<bool, T, T>", "less"),), "sortedBy"),
    BuiltinMemberSpec("mapTo", "Vector<U>", "method", (("__fn_ptr<U, T>", "fn"),), "mapTo"),
    BuiltinMemberSpec("min", "T", "method", (), "min"),
    BuiltinMemberSpec("max", "T", "method", (), "max"),
    BuiltinMemberSpec("sum", "T", "method", (), "sum"),
    BuiltinMemberSpec("join", "string", "method", (("string", "sep"),), "join"),
    BuiltinMemberSpec("joinToString", "string", "method", (("string", "sep"),), "joinToString"),
    BuiltinMemberSpec("filter", "Vector<T>", "method", (("__fn_ptr<bool, T>", "pred"),), "filter"),
    BuiltinMemberSpec("findIndex", "int", "method", (("__fn_ptr<bool, T>", "pred"),), "findIndex"),
    BuiltinMemberSpec("forEach", "void", "method", (("__fn_ptr<void, T>", "fn"),), "forEach"),
    BuiltinMemberSpec("map", "Vector<T>", "method", (("__fn_ptr<T, T>", "fn"),), "map"),
    BuiltinMemberSpec("any", "bool", "method", (("__fn_ptr<bool, T>", "pred"),), "any"),
    BuiltinMemberSpec("all", "bool", "method", (("__fn_ptr<bool, T>", "pred"),), "all"),
    BuiltinMemberSpec("reduce", "T", "method", (("T", "init"), ("__fn_ptr<T, T, T>", "fn"),), "reduce"),
    BuiltinMemberSpec("copy", "Vector<T>", "method", (), "copy"),
    BuiltinMemberSpec("removeAt", "void", "method", (("int", "idx"),), "removeAt"),
    BuiltinMemberSpec("iterLen", "int", "method", (), "iterLen"),
    BuiltinMemberSpec("iterGet", "T", "method", (("int", "i"),), "iterGet"),
)

MEMBER_TABLES: tuple[tuple[str, tuple[BuiltinMemberSpec, ...]], ...] = (
    ("string", STRING_MEMBERS),
    ("Atomic", ATOMIC_MEMBERS),
    ("Span", SPAN_MEMBERS),
    ("Array", ARRAY_MEMBERS),
    ("OwnedClosure", OWNEDCLOSURE_MEMBERS),
    ("CallbackRegistration", CALLBACKREGISTRATION_MEMBERS),
    ("ListNode", LISTNODE_MEMBERS),
    ("List", LIST_MEMBERS),
    ("Map", MAP_MEMBERS),
    ("Result", RESULT_MEMBERS),
    ("Set", SET_MEMBERS),
    ("SpscQueue", SPSCQUEUE_MEMBERS),
    ("State", STATE_MEMBERS),
    ("Vector", VECTOR_MEMBERS),
)


# ---------------------------------------------------------------------------
# Stdlib static method tables
# ---------------------------------------------------------------------------

# Generated from stdlib .btrc files
STDLIB_STATIC_METHODS: tuple[tuple[str, tuple[BuiltinMemberSpec, ...]], ...] = (
    ("UnixFileSystem", (
        BuiltinMemberSpec("chmodPath", "int", "method", (("string", "path"), ("int", "mode"),), "chmodPath"),
        BuiltinMemberSpec("mkdirPath", "int", "method", (("string", "path"), ("int", "mode"),), "mkdirPath"),
        BuiltinMemberSpec("mkdirOne", "int", "method", (("string", "path"), ("int", "mode"),), "mkdirOne"),
        BuiltinMemberSpec("mkdirp", "int", "method", (("string", "path"),), "mkdirp"),
        BuiltinMemberSpec("isCanonicalRoot", "bool", "method", (("string", "path"),), "isCanonicalRoot"),
        BuiltinMemberSpec("removeRecursivePath", "int", "method", (("string", "path"),), "removeRecursivePath"),
        BuiltinMemberSpec("removeRecursiveAtInspected", "int", "method", (("int", "parentDescriptor"), ("string", "name"), ("struct stat*", "inspected"),), "removeRecursiveAtInspected"),
        BuiltinMemberSpec("leaseDirectoryAt", "DirectoryLease", "method", (("int", "parentDescriptor"), ("string", "name"),), "leaseDirectoryAt"),
        BuiltinMemberSpec("removeRecursiveAtLease", "int", "method", (("int", "parentDescriptor"), ("string", "name"), ("DirectoryLease", "lease"),), "removeRecursiveAtLease"),
        BuiltinMemberSpec("removeRecursiveAt", "int", "method", (("int", "parentDescriptor"), ("string", "name"),), "removeRecursiveAt"),
        BuiltinMemberSpec("openDirectoryNoFollow", "int", "method", (("string", "path"),), "openDirectoryNoFollow"),
        BuiltinMemberSpec("deletionParentPath", "string", "method", (("string", "parent"),), "deletionParentPath"),
        BuiltinMemberSpec("removeRecursive", "int", "method", (("string", "path"),), "removeRecursive"),
        BuiltinMemberSpec("symlinkPath", "int", "method", (("string", "target"), ("string", "linkPath"),), "symlinkPath"),
        BuiltinMemberSpec("readLink", "string", "method", (("string", "path"),), "readLink"),
        BuiltinMemberSpec("currentDirectory", "string", "method", (), "currentDirectory"),
        BuiltinMemberSpec("realPath", "string", "method", (("string", "path"),), "realPath"),
        BuiltinMemberSpec("tempDir", "string", "method", (("string", "prefix"),), "tempDir"),
    )),
    ("PathTools", (
        BuiltinMemberSpec("shellQuote", "string", "method", (("string", "raw"),), "shellQuote"),
        BuiltinMemberSpec("isSeparatorFor", "bool", "method", (("char", "value"), ("bool", "windows"),), "isSeparatorFor"),
        BuiltinMemberSpec("hasDrivePrefixFor", "bool", "method", (("string", "path"), ("bool", "windows"),), "hasDrivePrefixFor"),
        BuiltinMemberSpec("isAbsoluteFor", "bool", "method", (("string", "path"), ("bool", "windows"),), "isAbsoluteFor"),
        BuiltinMemberSpec("isAbsolute", "bool", "method", (("string", "path"),), "isAbsolute"),
        BuiltinMemberSpec("isRootRelativeFor", "bool", "method", (("string", "path"), ("bool", "windows"),), "isRootRelativeFor"),
        BuiltinMemberSpec("rootLengthFor", "int", "method", (("string", "path"), ("bool", "windows"),), "rootLengthFor"),
        BuiltinMemberSpec("basename", "string", "method", (("string", "path"),), "basename"),
        BuiltinMemberSpec("dirname", "string", "method", (("string", "path"),), "dirname"),
        BuiltinMemberSpec("joinFor", "string", "method", (("string", "left"), ("string", "right"), ("bool", "windows"),), "joinFor"),
        BuiltinMemberSpec("join", "string", "method", (("string", "left"), ("string", "right"),), "join"),
        BuiltinMemberSpec("absolute", "string", "method", (("string", "path"),), "absolute"),
    )),
    ("FileSystem", (
        BuiltinMemberSpec("inspectExact", "FileSnapshotOutcome", "method", (("string", "path"),), "inspectExact"),
        BuiltinMemberSpec("openFileExact", "FileOpenOutcome", "method", (("string", "path"),), "openFileExact"),
        BuiltinMemberSpec("openRegularFileSnapshot", "RegularFileSnapshotOpenOutcome", "method", (("string", "path"), ("long long", "maximumBytes"),), "openRegularFileSnapshot"),
        BuiltinMemberSpec("openDirectoryExact", "DirectoryOpenOutcome", "method", (("string", "path"),), "openDirectoryExact"),
        BuiltinMemberSpec("createTemporaryDirectory", "TemporaryDirectoryOpenOutcome", "method", (("string", "prefix"),), "createTemporaryDirectory"),
        BuiltinMemberSpec("openPrivateDirectory", "PrivateDirectoryOpenOutcome", "method", (("string", "absolutePath"),), "openPrivateDirectory"),
        BuiltinMemberSpec("ownedHandleInventory", "FileSystemHandleInventory", "method", (), "ownedHandleInventory"),
        BuiltinMemberSpec("exists", "bool", "method", (("string", "path"),), "exists"),
        BuiltinMemberSpec("isDir", "bool", "method", (("string", "path"),), "isDir"),
        BuiltinMemberSpec("isFile", "bool", "method", (("string", "path"),), "isFile"),
        BuiltinMemberSpec("isSymlink", "bool", "method", (("string", "path"),), "isSymlink"),
        BuiltinMemberSpec("chmod", "int", "method", (("string", "path"), ("int", "mode"),), "chmod"),
        BuiltinMemberSpec("mkdir", "int", "method", (("string", "path"), ("int", "mode"),), "mkdir"),
        BuiltinMemberSpec("mkdirp", "int", "method", (("string", "path"),), "mkdirp"),
        BuiltinMemberSpec("removeRecursive", "int", "method", (("string", "path"),), "removeRecursive"),
        BuiltinMemberSpec("symlink", "int", "method", (("string", "target"), ("string", "linkPath"),), "symlink"),
        BuiltinMemberSpec("readLink", "string", "method", (("string", "path"),), "readLink"),
        BuiltinMemberSpec("currentDirectory", "string", "method", (), "currentDirectory"),
        BuiltinMemberSpec("absolutePath", "string", "method", (("string", "path"),), "absolutePath"),
        BuiltinMemberSpec("tempDir", "string", "method", (("string", "prefix"),), "tempDir"),
        BuiltinMemberSpec("listDir", "Vector<string>", "method", (("string", "path"),), "listDir"),
        BuiltinMemberSpec("readText", "string", "method", (("string", "path"),), "readText"),
        BuiltinMemberSpec("writeText", "bool", "method", (("string", "path"), ("string", "content"),), "writeText"),
    )),
    ("FileSystemDiagnostics", (
        BuiltinMemberSpec("ownedHandleInventory", "FileSystemHandleInventory", "method", (), "ownedHandleInventory"),
    )),
    ("BackgroundJobWork", (
        BuiltinMemberSpec("cancellationRequested", "bool", "method", (("void*", "cancellation"),), "cancellationRequested"),
    )),
    ("Console", (
        BuiltinMemberSpec("log", "void", "method", (("string", "msg"),), "log"),
        BuiltinMemberSpec("error", "void", "method", (("string", "msg"),), "error"),
        BuiltinMemberSpec("write", "void", "method", (("string", "msg"),), "write"),
        BuiltinMemberSpec("writeLine", "void", "method", (("string", "msg"),), "writeLine"),
    )),
    ("DaemonControlRecord", (
        BuiltinMemberSpec("validToken", "bool", "method", (("string", "token"),), "validToken"),
        BuiltinMemberSpec("parsePid", "int", "method", (("string", "text"),), "parsePid"),
        BuiltinMemberSpec("parse", "DaemonControlRecord", "method", (("string", "content"),), "parse"),
    )),
    ("DaemonControlClock", (
        BuiltinMemberSpec("millisecondsFrom", "long long", "method", (("uintmax_t", "seconds"), ("long", "nanoseconds"),), "millisecondsFrom"),
        BuiltinMemberSpec("milliseconds", "long long", "method", (), "milliseconds"),
        BuiltinMemberSpec("deadline", "long long", "method", (("long long", "now"), ("int", "timeoutMilliseconds"),), "deadline"),
        BuiltinMemberSpec("pause", "void", "method", (), "pause"),
        BuiltinMemberSpec("before", "bool", "method", (("long long", "deadline"),), "before"),
    )),
    ("DaemonControlPaths", (
        BuiltinMemberSpec("validDaemonName", "bool", "method", (("string", "name"),), "validDaemonName"),
        BuiltinMemberSpec("absolute", "bool", "method", (("string", "path"),), "absolute"),
        BuiltinMemberSpec("defaultDirectory", "string", "method", (), "defaultDirectory"),
        BuiltinMemberSpec("stop", "string", "method", (("string", "pidFile"), ("string", "token"),), "stop"),
        BuiltinMemberSpec("probePrefix", "string", "method", (("string", "pidFile"), ("string", "token"),), "probePrefix"),
        BuiltinMemberSpec("probe", "string", "method", (("string", "pidFile"), ("string", "token"), ("string", "challenge"),), "probe"),
        BuiltinMemberSpec("acknowledgement", "string", "method", (("string", "probe"),), "acknowledgement"),
    )),
    ("DaemonControlFiles", (
        BuiltinMemberSpec("canonicalPrivateDirectory", "bool", "method", (("string", "path"),), "canonicalPrivateDirectory"),
        BuiltinMemberSpec("ownedHome", "bool", "method", (("string", "path"),), "ownedHome"),
        BuiltinMemberSpec("createPrivateDirectory", "bool", "method", (("string", "path"),), "createPrivateDirectory"),
        BuiltinMemberSpec("ensureDefaultDirectory", "bool", "method", (), "ensureDefaultDirectory"),
        BuiltinMemberSpec("secureParent", "bool", "method", (("string", "path"),), "secureParent"),
        BuiltinMemberSpec("canonicalFilePath", "string", "method", (("string", "path"),), "canonicalFilePath"),
        BuiltinMemberSpec("secureMetadata", "bool", "method", (("string", "path"), ("struct stat*", "status"),), "secureMetadata"),
        BuiltinMemberSpec("read", "string", "method", (("string", "path"),), "read"),
        BuiltinMemberSpec("create", "bool", "method", (("string", "path"), ("string", "content"),), "create"),
        BuiltinMemberSpec("remove", "bool", "method", (("string", "path"),), "remove"),
        BuiltinMemberSpec("prepareLog", "bool", "method", (("string", "path"),), "prepareLog"),
        BuiltinMemberSpec("absent", "bool", "method", (("string", "path"),), "absent"),
        BuiltinMemberSpec("safeLogPath", "bool", "method", (("string", "path"),), "safeLogPath"),
    )),
    ("DaemonControlProtocol", (
        BuiltinMemberSpec("pauseBeforeRetry", "bool", "method", (("long long", "deadline"),), "pauseBeforeRetry"),
        BuiltinMemberSpec("randomToken", "string", "method", (), "randomToken"),
        BuiltinMemberSpec("record", "DaemonControlRecord", "method", (("string", "pidFile"),), "record"),
        BuiltinMemberSpec("probe", "bool", "method", (("string", "pidFile"), ("DaemonControlRecord", "record"), ("int", "timeoutMilliseconds"),), "probe"),
        BuiltinMemberSpec("waitForRecord", "bool", "method", (("string", "pidFile"), ("int", "timeoutMilliseconds"),), "waitForRecord"),
        BuiltinMemberSpec("waitForRemoval", "bool", "method", (("string", "pidFile"), ("DaemonControlRecord", "original"), ("int", "timeoutMilliseconds"),), "waitForRemoval"),
    )),
    ("GraphCli", (
        BuiltinMemberSpec("args", "Map<string, string>", "method", (("CliArgs", "args"), ("int", "startIndex"),), "args"),
        BuiltinMemberSpec("targets", "Vector<string>", "method", (("CliArgs", "args"), ("int", "startIndex"),), "targets"),
    )),
    ("GraphReport", (
        BuiltinMemberSpec("list", "void", "method", (("ExecutionGraph", "graph"),), "list"),
    )),
    ("GraphValidation", (
        BuiltinMemberSpec("nodeIds", "Vector<string>", "method", (("ExecutionGraph", "graph"),), "nodeIds"),
        BuiltinMemberSpec("error", "string", "method", (("ExecutionGraph", "graph"),), "error"),
    )),
    ("GraphParser", (
        BuiltinMemberSpec("node", "GraphNode", "method", (("string", "objectText"),), "node"),
        BuiltinMemberSpec("readFile", "ExecutionGraph", "method", (("string", "path"),), "readFile"),
    )),
    ("Browser", (
        BuiltinMemberSpec("open", "void", "method", (("string", "url"),), "open"),
    )),
    ("HttpFraming", (
        BuiltinMemberSpec("hexVal", "int", "method", (("char", "ch"),), "hexVal"),
        BuiltinMemberSpec("tokenChar", "bool", "method", (("char", "ch"),), "tokenChar"),
        BuiltinMemberSpec("token", "bool", "method", (("string", "value"),), "token"),
        BuiltinMemberSpec("fieldValue", "bool", "method", (("string", "value"),), "fieldValue"),
        BuiltinMemberSpec("requestTarget", "bool", "method", (("string", "value"),), "requestTarget"),
        BuiltinMemberSpec("headerLine", "bool", "method", (("string", "line"),), "headerLine"),
        BuiltinMemberSpec("headerEnd", "int", "method", (("Bytes", "raw"),), "headerEnd"),
        BuiltinMemberSpec("contentLength", "int", "method", (("string", "head"),), "contentLength"),
        BuiltinMemberSpec("transferEncoding", "int", "method", (("string", "head"),), "transferEncoding"),
        BuiltinMemberSpec("trailerLine", "bool", "method", (("Bytes", "raw"), ("int", "start"), ("int", "end"),), "trailerLine"),
        BuiltinMemberSpec("chunkedEnd", "int", "method", (("Bytes", "raw"), ("int", "bodyStart"), ("int", "maxBodyBytes"), ("int", "maxTrailerBytes"),), "chunkedEnd"),
        BuiltinMemberSpec("decodeChunked", "Bytes", "method", (("Bytes", "body"), ("int", "maxBodyBytes"), ("int", "maxTrailerBytes"),), "decodeChunked"),
    )),
    ("HttpUrl", (
        BuiltinMemberSpec("decode", "string", "method", (("string", "value"),), "decode"),
        BuiltinMemberSpec("encode", "string", "method", (("string", "value"),), "encode"),
    )),
    ("HttpStatus", (
        BuiltinMemberSpec("reason", "string", "method", (("int", "status"),), "reason"),
    )),
    ("HttpResponseHeaders", (
        BuiltinMemberSpec("reserved", "bool", "method", (("string", "name"),), "reserved"),
    )),
    ("HttpSocket", (
        BuiltinMemberSpec("configureDescriptor", "bool", "method", (("int", "descriptor"), ("bool", "nonblocking"),), "configureDescriptor"),
        BuiltinMemberSpec("sendNoSignal", "long long", "method", (("int", "descriptor"), ("char*", "data"), ("size_t", "length"),), "sendNoSignal"),
        BuiltinMemberSpec("nowMilliseconds", "long long", "method", (), "nowMilliseconds"),
        BuiltinMemberSpec("deadlineAfter", "long long", "method", (("int", "timeoutSecs"),), "deadlineAfter"),
        BuiltinMemberSpec("waitFor", "bool", "method", (("int", "descriptor"), ("short", "events"), ("long long", "deadline"),), "waitFor"),
        BuiltinMemberSpec("openListener", "int", "method", (("int", "port"), ("bool", "bindAny"),), "openListener"),
        BuiltinMemberSpec("acceptConnection", "int", "method", (("int", "listener"), ("int", "timeoutSecs"),), "acceptConnection"),
        BuiltinMemberSpec("closeConnection", "void", "method", (("int", "descriptor"),), "closeConnection"),
        BuiltinMemberSpec("emptyBytes", "Bytes", "method", (), "emptyBytes"),
        BuiltinMemberSpec("readRequest", "Bytes", "method", (("int", "descriptor"), ("int", "maxHeaderBytes"), ("int", "maxBodyBytes"), ("int", "maxRequestBytes"), ("int", "timeoutSecs"),), "readRequest"),
        BuiltinMemberSpec("sendAllUntil", "bool", "method", (("int", "descriptor"), ("string", "data"), ("long long", "deadline"),), "sendAllUntil"),
        BuiltinMemberSpec("sendAll", "bool", "method", (("int", "descriptor"), ("string", "data"), ("int", "timeoutSecs"),), "sendAll"),
    )),
    ("ImageBinary", (
        BuiltinMemberSpec("has", "bool", "method", (("Bytes", "bytes"), ("long long", "offset"), ("long long", "count"),), "has"),
        BuiltinMemberSpec("u16", "int", "method", (("Bytes", "bytes"), ("int", "offset"),), "u16"),
        BuiltinMemberSpec("u32", "long long", "method", (("Bytes", "bytes"), ("int", "offset"),), "u32"),
        BuiltinMemberSpec("i32", "long long", "method", (("Bytes", "bytes"), ("int", "offset"),), "i32"),
        BuiltinMemberSpec("appendU16", "void", "method", (("Bytes", "bytes"), ("int", "value"),), "appendU16"),
        BuiltinMemberSpec("appendU32", "void", "method", (("Bytes", "bytes"), ("long long", "value"),), "appendU32"),
    )),
    ("ImageIO", (
        BuiltinMemberSpec("decode", "ImageLoad", "method", (("Bytes", "bytes"),), "decode"),
        BuiltinMemberSpec("decodePpm", "ImageLoad", "method", (("Bytes", "bytes"),), "decodePpm"),
        BuiltinMemberSpec("decodeBmp", "ImageLoad", "method", (("Bytes", "bytes"),), "decodeBmp"),
        BuiltinMemberSpec("encodePpm", "Bytes", "method", (("Image", "image"),), "encodePpm"),
        BuiltinMemberSpec("encodeBmp", "Bytes", "method", (("Image", "image"), ("int", "bitsPerPixel"), ("bool", "topDown"),), "encodeBmp"),
        BuiltinMemberSpec("readImageFile", "ImageFileRead", "method", (("string", "path"), ("string", "description"),), "readImageFile"),
        BuiltinMemberSpec("load", "ImageLoad", "method", (("string", "path"),), "load"),
        BuiltinMemberSpec("loadPpm", "ImageLoad", "method", (("string", "path"),), "loadPpm"),
        BuiltinMemberSpec("loadBmp", "ImageLoad", "method", (("string", "path"),), "loadBmp"),
        BuiltinMemberSpec("savePpm", "bool", "method", (("Image", "image"), ("string", "path"),), "savePpm"),
        BuiltinMemberSpec("saveBmp", "bool", "method", (("Image", "image"), ("string", "path"), ("int", "bitsPerPixel"), ("bool", "topDown"),), "saveBmp"),
    )),
    ("Path", (
        BuiltinMemberSpec("exists", "bool", "method", (("string", "path"),), "exists"),
        BuiltinMemberSpec("readAll", "string", "method", (("string", "path"),), "readAll"),
        BuiltinMemberSpec("writeAll", "bool", "method", (("string", "path"), ("string", "content"),), "writeAll"),
    )),
    ("JsonNum", (
        BuiltinMemberSpec("toDouble", "double", "method", (("string", "token"),), "toDouble"),
        BuiltinMemberSpec("isFinite", "bool", "method", (("double", "value"),), "isFinite"),
        BuiltinMemberSpec("format", "string", "method", (("double", "value"), ("bool", "isInt"),), "format"),
        BuiltinMemberSpec("charFromCode", "string", "method", (("int", "code"),), "charFromCode"),
        BuiltinMemberSpec("uEscape", "string", "method", (("int", "code"),), "uEscape"),
        BuiltinMemberSpec("utf8", "string", "method", (("int", "cp"),), "utf8"),
    )),
    ("JsonText", (
        BuiltinMemberSpec("slice", "string", "method", (("string", "text"), ("int", "start"), ("int", "end"),), "slice"),
        BuiltinMemberSpec("unescape", "string", "method", (("string", "text"),), "unescape"),
        BuiltinMemberSpec("stringEnd", "int", "method", (("string", "text"), ("int", "start"),), "stringEnd"),
        BuiltinMemberSpec("balancedEnd", "int", "method", (("string", "text"), ("int", "start"),), "balancedEnd"),
        BuiltinMemberSpec("skipSpaces", "int", "method", (("string", "text"), ("int", "i"),), "skipSpaces"),
        BuiltinMemberSpec("isInt", "bool", "method", (("string", "text"),), "isInt"),
        BuiltinMemberSpec("toIntOr", "int", "method", (("string", "text"), ("int", "fallback"),), "toIntOr"),
        BuiltinMemberSpec("keyPosition", "int", "method", (("string", "text"), ("string", "key"),), "keyPosition"),
        BuiltinMemberSpec("valueStart", "int", "method", (("string", "text"), ("string", "key"),), "valueStart"),
        BuiltinMemberSpec("parseStringValue", "string", "method", (("string", "text"), ("int", "i"), ("string", "fallback"),), "parseStringValue"),
        BuiltinMemberSpec("field", "string", "method", (("string", "text"), ("string", "key"), ("string", "fallback"),), "field"),
        BuiltinMemberSpec("intField", "int", "method", (("string", "text"), ("string", "key"), ("int", "fallback"),), "intField"),
        BuiltinMemberSpec("objectField", "string", "method", (("string", "text"), ("string", "key"),), "objectField"),
        BuiltinMemberSpec("objectPath", "string", "method", (("string", "text"), ("Vector<string>", "path"),), "objectPath"),
        BuiltinMemberSpec("fieldPath", "string", "method", (("string", "text"), ("Vector<string>", "path"), ("string", "fallback"),), "fieldPath"),
        BuiltinMemberSpec("stringArray", "Vector<string>", "method", (("string", "text"), ("string", "key"),), "stringArray"),
        BuiltinMemberSpec("objectArray", "Vector<string>", "method", (("string", "text"), ("string", "key"),), "objectArray"),
        BuiltinMemberSpec("objectMap", "Map<string, string>", "method", (("string", "objectText"),), "objectMap"),
        BuiltinMemberSpec("argsObject", "Map<string, string>", "method", (("string", "text"),), "argsObject"),
        BuiltinMemberSpec("expand", "string", "method", (("string", "text"), ("Map<string, string>", "args"),), "expand"),
        BuiltinMemberSpec("putArgPair", "void", "method", (("Map<string, string>", "result"), ("string", "pair"),), "putArgPair"),
    )),
    ("Json", (
        BuiltinMemberSpec("esc", "string", "method", (("string", "s"),), "esc"),
        BuiltinMemberSpec("str", "string", "method", (("string", "s"),), "str"),
        BuiltinMemberSpec("getString", "string", "method", (("string", "json"), ("string", "key"),), "getString"),
        BuiltinMemberSpec("getStringAfter", "string", "method", (("string", "json"), ("string", "anchor"), ("string", "key"),), "getStringAfter"),
        BuiltinMemberSpec("getStringFrom", "string", "method", (("string", "json"), ("string", "key"), ("int", "from"),), "getStringFrom"),
    )),
    ("Math", (
        BuiltinMemberSpec("PI", "float", "method", (), "PI"),
        BuiltinMemberSpec("E", "float", "method", (), "E"),
        BuiltinMemberSpec("TAU", "float", "method", (), "TAU"),
        BuiltinMemberSpec("INF", "float", "method", (), "INF"),
        BuiltinMemberSpec("abs", "int", "method", (("int", "x"),), "abs"),
        BuiltinMemberSpec("fabs", "float", "method", (("float", "x"),), "fabs"),
        BuiltinMemberSpec("max", "int", "method", (("int", "a"), ("int", "b"),), "max"),
        BuiltinMemberSpec("min", "int", "method", (("int", "a"), ("int", "b"),), "min"),
        BuiltinMemberSpec("fmax", "float", "method", (("float", "a"), ("float", "b"),), "fmax"),
        BuiltinMemberSpec("fmin", "float", "method", (("float", "a"), ("float", "b"),), "fmin"),
        BuiltinMemberSpec("clamp", "int", "method", (("int", "x"), ("int", "lo"), ("int", "hi"),), "clamp"),
        BuiltinMemberSpec("power", "float", "method", (("float", "base"), ("int", "exp"),), "power"),
        BuiltinMemberSpec("sqrt", "float", "method", (("float", "x"),), "sqrt"),
        BuiltinMemberSpec("factorial", "int", "method", (("int", "n"),), "factorial"),
        BuiltinMemberSpec("gcd", "int", "method", (("int", "a"), ("int", "b"),), "gcd"),
        BuiltinMemberSpec("lcm", "int", "method", (("int", "a"), ("int", "b"),), "lcm"),
        BuiltinMemberSpec("fibonacci", "int", "method", (("int", "n"),), "fibonacci"),
        BuiltinMemberSpec("isPrime", "bool", "method", (("int", "n"),), "isPrime"),
        BuiltinMemberSpec("isEven", "bool", "method", (("int", "n"),), "isEven"),
        BuiltinMemberSpec("isOdd", "bool", "method", (("int", "n"),), "isOdd"),
        BuiltinMemberSpec("sum", "int", "method", (("Vector<int>", "items"),), "sum"),
        BuiltinMemberSpec("fsum", "float", "method", (("Vector<float>", "items"),), "fsum"),
        BuiltinMemberSpec("sin", "float", "method", (("float", "x"),), "sin"),
        BuiltinMemberSpec("cos", "float", "method", (("float", "x"),), "cos"),
        BuiltinMemberSpec("tan", "float", "method", (("float", "x"),), "tan"),
        BuiltinMemberSpec("asin", "float", "method", (("float", "x"),), "asin"),
        BuiltinMemberSpec("acos", "float", "method", (("float", "x"),), "acos"),
        BuiltinMemberSpec("atan", "float", "method", (("float", "x"),), "atan"),
        BuiltinMemberSpec("atan2", "float", "method", (("float", "y"), ("float", "x"),), "atan2"),
        BuiltinMemberSpec("ceil", "float", "method", (("float", "x"),), "ceil"),
        BuiltinMemberSpec("floor", "float", "method", (("float", "x"),), "floor"),
        BuiltinMemberSpec("round", "int", "method", (("float", "x"),), "round"),
        BuiltinMemberSpec("truncate", "int", "method", (("float", "x"),), "truncate"),
        BuiltinMemberSpec("log", "float", "method", (("float", "x"),), "log"),
        BuiltinMemberSpec("log10", "float", "method", (("float", "x"),), "log10"),
        BuiltinMemberSpec("log2", "float", "method", (("float", "x"),), "log2"),
        BuiltinMemberSpec("exp", "float", "method", (("float", "x"),), "exp"),
        BuiltinMemberSpec("toRadians", "float", "method", (("float", "degrees"),), "toRadians"),
        BuiltinMemberSpec("toDegrees", "float", "method", (("float", "radians"),), "toDegrees"),
        BuiltinMemberSpec("fclamp", "float", "method", (("float", "val"), ("float", "lo"), ("float", "hi"),), "fclamp"),
        BuiltinMemberSpec("sign", "int", "method", (("int", "x"),), "sign"),
        BuiltinMemberSpec("fsign", "float", "method", (("float", "x"),), "fsign"),
    )),
    ("NativeUiStyle", (
        BuiltinMemberSpec("decimal", "bool", "method", (("string", "value"), ("bool", "allowZero"),), "decimal"),
        BuiltinMemberSpec("pixels", "bool", "method", (("string", "value"), ("bool", "allowZero"),), "pixels"),
        BuiltinMemberSpec("hexDigit", "bool", "method", (("char", "value"),), "hexDigit"),
        BuiltinMemberSpec("color", "bool", "method", (("string", "value"),), "color"),
        BuiltinMemberSpec("validate", "NativeUiStyleError", "method", (("string", "css"),), "validate"),
        BuiltinMemberSpec("validateClassName", "NativeUiStyleError", "method", (("string", "value"),), "validateClassName"),
    )),
    ("UnixPattern", (
        BuiltinMemberSpec("matches", "bool", "method", (("string", "pattern"), ("string", "text"),), "matches"),
    )),
    ("Pattern", (
        BuiltinMemberSpec("matches", "bool", "method", (("string", "pattern"), ("string", "text"),), "matches"),
        BuiltinMemberSpec("anyMatches", "bool", "method", (("Vector<string>", "patterns"), ("string", "text"),), "anyMatches"),
    )),
    ("UnixPlatform", (
        BuiltinMemberSpec("pid", "int", "method", (), "pid"),
        BuiltinMemberSpec("euid", "int", "method", (), "euid"),
    )),
    ("Platform", (
        BuiltinMemberSpec("isUnix", "bool", "method", (), "isUnix"),
        BuiltinMemberSpec("isWindows", "bool", "method", (), "isWindows"),
        BuiltinMemberSpec("pathSeparator", "string", "method", (), "pathSeparator"),
        BuiltinMemberSpec("pid", "int", "method", (), "pid"),
        BuiltinMemberSpec("euid", "int", "method", (), "euid"),
        BuiltinMemberSpec("isRoot", "bool", "method", (), "isRoot"),
    )),
    ("Environment", (
        BuiltinMemberSpec("get", "string", "method", (("string", "name"), ("string", "fallback"),), "get"),
        BuiltinMemberSpec("has", "bool", "method", (("string", "name"),), "has"),
    )),
    ("UnixProcess", (
        BuiltinMemberSpec("system", "ProcessStatus", "method", (("string", "command"),), "system"),
        BuiltinMemberSpec("pipe", "UnixPipe", "method", (("string", "command"),), "pipe"),
    )),
    ("ShellWords", (
        BuiltinMemberSpec("isEnvNameStart", "bool", "method", (("char", "c"),), "isEnvNameStart"),
        BuiltinMemberSpec("isEnvNameChar", "bool", "method", (("char", "c"),), "isEnvNameChar"),
        BuiltinMemberSpec("isEnvName", "bool", "method", (("string", "name"),), "isEnvName"),
        BuiltinMemberSpec("isSafeArgChar", "bool", "method", (("char", "c"),), "isSafeArgChar"),
        BuiltinMemberSpec("isSafeArg", "bool", "method", (("string", "raw"),), "isSafeArg"),
        BuiltinMemberSpec("quote", "string", "method", (("string", "raw"),), "quote"),
        BuiltinMemberSpec("redact", "string", "method", (("string", "text"), ("string", "sensitive"),), "redact"),
        BuiltinMemberSpec("envAssignment", "string", "method", (("string", "item"),), "envAssignment"),
    )),
    ("CommandOutput", (
        BuiltinMemberSpec("collect", "string", "method", (), "collect"),
        BuiltinMemberSpec("stream", "string", "method", (), "stream"),
        BuiltinMemberSpec("combine", "string", "method", (), "combine"),
        BuiltinMemberSpec("suppress", "string", "method", (), "suppress"),
        BuiltinMemberSpec("valid", "bool", "method", (("string", "mode"),), "valid"),
    )),
    ("CommandEnvironment", (
        BuiltinMemberSpec("empty", "Vector<string>", "method", (), "empty"),
    )),
    ("ChildDescriptorMappings", (
        BuiltinMemberSpec("empty", "Vector<ChildDescriptorMapping>", "method", (), "empty"),
    )),
    ("ChildProcessClock", (
        BuiltinMemberSpec("millisecondsFrom", "long long", "method", (("uintmax_t", "seconds"), ("long", "nanoseconds"),), "millisecondsFrom"),
        BuiltinMemberSpec("milliseconds", "long long", "method", (), "milliseconds"),
        BuiltinMemberSpec("deadline", "long long", "method", (("long long", "now"), ("int", "timeoutMilliseconds"),), "deadline"),
    )),
    ("ChildProcessEnvironment", (
        BuiltinMemberSpec("copyEntry", "char*", "method", (("string", "value"),), "copyEntry"),
        BuiltinMemberSpec("freeEntries", "void", "method", (("char**", "environment"),), "freeEntries"),
        BuiltinMemberSpec("assignmentHasName", "bool", "method", (("string", "assignment"), ("string", "name"),), "assignmentHasName"),
        BuiltinMemberSpec("assignmentsShareName", "bool", "method", (("string", "left"), ("string", "right"),), "assignmentsShareName"),
        BuiltinMemberSpec("replaced", "bool", "method", (("string", "inherited"), ("Vector<string>", "environment"), ("Vector<string>", "unsetEnvironment"),), "replaced"),
        BuiltinMemberSpec("build", "char**", "method", (("Vector<string>", "environment"), ("Vector<string>", "unsetEnvironment"),), "build"),
    )),
    ("ChildProcessArguments", (
        BuiltinMemberSpec("build", "char**", "method", (("string", "executable"), ("Vector<string>", "arguments"),), "build"),
        BuiltinMemberSpec("freeEntries", "void", "method", (("char**", "arguments"),), "freeEntries"),
    )),
    ("ChildProcessExecutable", (
        BuiltinMemberSpec("join", "string", "method", (("string", "left"), ("string", "right"),), "join"),
        BuiltinMemberSpec("currentDirectory", "string", "method", (), "currentDirectory"),
        BuiltinMemberSpec("workingDirectory", "string", "method", (("string", "cwd"),), "workingDirectory"),
        BuiltinMemberSpec("searchPath", "string", "method", (("Vector<string>", "environment"), ("Vector<string>", "unsetEnvironment"),), "searchPath"),
        BuiltinMemberSpec("resolve", "string", "method", (("string", "executable"), ("string", "cwd"), ("Vector<string>", "environment"), ("Vector<string>", "unsetEnvironment"),), "resolve"),
    )),
    ("ChildProcess", (
        BuiltinMemberSpec("descriptorCloseBound", "int", "method", (), "descriptorCloseBound"),
        BuiltinMemberSpec("closeDescriptorsForExec", "int", "method", (("int", "bound"),), "closeDescriptorsForExec"),
        BuiltinMemberSpec("inheritsOnExec", "bool", "method", (("int", "descriptor"),), "inheritsOnExec"),
        BuiltinMemberSpec("validateArguments", "void", "method", (("Vector<string>", "arguments"),), "validateArguments"),
        BuiltinMemberSpec("moveOutsideStandardStreams", "int", "method", (("int*", "descriptor"),), "moveOutsideStandardStreams"),
        BuiltinMemberSpec("childSourceOutsideStandardStreams", "int", "method", (("int", "descriptor"),), "childSourceOutsideStandardStreams"),
        BuiltinMemberSpec("closeLeasedDescriptors", "void", "method", (("int*", "descriptors"), ("int", "count"),), "closeLeasedDescriptors"),
        BuiltinMemberSpec("validateEnvironment", "void", "method", (("Vector<string>", "environment"), ("Vector<string>", "unsetEnvironment"),), "validateEnvironment"),
        BuiltinMemberSpec("closePipe", "void", "method", (("int*", "descriptors"),), "closePipe"),
        BuiltinMemberSpec("openPipe", "int", "method", (("int*", "descriptors"),), "openPipe"),
        BuiltinMemberSpec("failure", "ExecResult", "method", (("string", "command"), ("string", "message"),), "failure"),
        BuiltinMemberSpec("render", "string", "method", (("string", "executable"), ("Vector<string>", "arguments"),), "render"),
        BuiltinMemberSpec("run", "ExecResult", "method", (("string", "executable"), ("Vector<string>", "arguments"), ("string", "cwd"), ("Vector<string>", "environment"), ("Vector<string>", "unsetEnvironment"), ("int", "timeoutMilliseconds"), ("int", "maxStdoutBytes"), ("int", "maxStderrBytes"), ("string", "stdinData"), ("string", "stdout"), ("string", "stderr"), ("int", "executableDescriptor"), ("Vector<ChildDescriptorMapping>", "descriptorMappings"), ("int", "workingDirectoryDescriptor"), ("bool", "foreground"),), "run"),
    )),
    ("Regex", (
        BuiltinMemberSpec("checkedLength", "int", "method", (("string", "text"),), "checkedLength"),
        BuiltinMemberSpec("capacityFor", "int", "method", (("int", "current"), ("long long", "required"),), "capacityFor"),
        BuiltinMemberSpec("slice", "string", "method", (("string", "text"), ("int", "so"), ("int", "eo"),), "slice"),
        BuiltinMemberSpec("warn", "void", "method", (("string", "pattern"),), "warn"),
        BuiltinMemberSpec("matches", "bool", "method", (("string", "pattern"), ("string", "text"),), "matches"),
        BuiltinMemberSpec("fullMatch", "bool", "method", (("string", "pattern"), ("string", "text"),), "fullMatch"),
        BuiltinMemberSpec("find", "int", "method", (("string", "pattern"), ("string", "text"),), "find"),
        BuiltinMemberSpec("first", "string", "method", (("string", "pattern"), ("string", "text"),), "first"),
        BuiltinMemberSpec("findAll", "Vector<string>", "method", (("string", "pattern"), ("string", "text"),), "findAll"),
        BuiltinMemberSpec("replace", "string", "method", (("string", "pattern"), ("string", "text"), ("string", "replacement"),), "replace"),
        BuiltinMemberSpec("replaceAll", "string", "method", (("string", "pattern"), ("string", "text"), ("string", "replacement"),), "replaceAll"),
        BuiltinMemberSpec("subst", "string", "method", (("string", "pattern"), ("string", "text"), ("string", "replacement"), ("bool", "all"),), "subst"),
    )),
    ("Strings", (
        BuiltinMemberSpec("checkedLength", "int", "method", (("string", "s"),), "checkedLength"),
        BuiltinMemberSpec("copy", "string", "method", (("string", "s"),), "copy"),
        BuiltinMemberSpec("repeat", "string", "method", (("string", "s"), ("int", "count"),), "repeat"),
        BuiltinMemberSpec("join", "string", "method", (("Vector<string>", "items"), ("string", "sep"),), "join"),
        BuiltinMemberSpec("replace", "string", "method", (("string", "s"), ("string", "old"), ("string", "replacement"),), "replace"),
        BuiltinMemberSpec("split", "Vector<string>", "method", (("string", "s"), ("string", "delim"),), "split"),
        BuiltinMemberSpec("isDigit", "bool", "method", (("char", "c"),), "isDigit"),
        BuiltinMemberSpec("isAlpha", "bool", "method", (("char", "c"),), "isAlpha"),
        BuiltinMemberSpec("isAlnum", "bool", "method", (("char", "c"),), "isAlnum"),
        BuiltinMemberSpec("isSpace", "bool", "method", (("char", "c"),), "isSpace"),
        BuiltinMemberSpec("toInt", "int", "method", (("string", "s"),), "toInt"),
        BuiltinMemberSpec("toFloat", "float", "method", (("string", "s"),), "toFloat"),
        BuiltinMemberSpec("count", "int", "method", (("string", "s"), ("string", "sub"),), "count"),
        BuiltinMemberSpec("find", "int", "method", (("string", "s"), ("string", "sub"), ("int", "start"),), "find"),
        BuiltinMemberSpec("rfind", "int", "method", (("string", "s"), ("string", "sub"),), "rfind"),
        BuiltinMemberSpec("compare", "int", "method", (("string", "left"), ("string", "right"),), "compare"),
        BuiltinMemberSpec("lessThan", "bool", "method", (("string", "left"), ("string", "right"),), "lessThan"),
        BuiltinMemberSpec("capitalize", "string", "method", (("string", "s"),), "capitalize"),
        BuiltinMemberSpec("title", "string", "method", (("string", "s"),), "title"),
        BuiltinMemberSpec("swapCase", "string", "method", (("string", "s"),), "swapCase"),
        BuiltinMemberSpec("padLeft", "string", "method", (("string", "s"), ("int", "width"), ("char", "fill"),), "padLeft"),
        BuiltinMemberSpec("padRight", "string", "method", (("string", "s"), ("int", "width"), ("char", "fill"),), "padRight"),
        BuiltinMemberSpec("center", "string", "method", (("string", "s"), ("int", "width"), ("char", "fill"),), "center"),
        BuiltinMemberSpec("lstrip", "string", "method", (("string", "s"),), "lstrip"),
        BuiltinMemberSpec("rstrip", "string", "method", (("string", "s"),), "rstrip"),
        BuiltinMemberSpec("removePrefix", "string", "method", (("string", "s"), ("string", "prefix"),), "removePrefix"),
        BuiltinMemberSpec("fromInt", "string", "method", (("int", "n"),), "fromInt"),
        BuiltinMemberSpec("fromFloat", "string", "method", (("float", "f"),), "fromFloat"),
        BuiltinMemberSpec("isDigitStr", "bool", "method", (("string", "s"),), "isDigitStr"),
        BuiltinMemberSpec("isAlphaStr", "bool", "method", (("string", "s"),), "isAlphaStr"),
        BuiltinMemberSpec("isBlank", "bool", "method", (("string", "s"),), "isBlank"),
    )),
    ("Terminal", (
        BuiltinMemberSpec("readLine", "string", "method", (), "readLine"),
        BuiltinMemberSpec("prompt", "string", "method", (("string", "label"),), "prompt"),
        BuiltinMemberSpec("promptPassword", "string", "method", (("string", "label"),), "promptPassword"),
    )),
    ("UnixPamPassword", (
        BuiltinMemberSpec("safeAccountArgument", "bool", "method", (("string", "value"),), "safeAccountArgument"),
        BuiltinMemberSpec("canonicalAccountArgument", "string", "method", (("string", "requested"), ("string", "canonical"),), "canonicalAccountArgument"),
        BuiltinMemberSpec("safeSecret", "bool", "method", (("string", "value"),), "safeSecret"),
        BuiltinMemberSpec("passwdExecutable", "string", "method", (), "passwdExecutable"),
        BuiltinMemberSpec("responseCountFor", "int", "method", (("uid_t", "effectiveUser"), ("uid_t", "targetUser"),), "responseCountFor"),
        BuiltinMemberSpec("maySendResponse", "bool", "method", (("int", "sent"), ("int", "selected"), ("bool", "promptSeen"),), "maySendResponse"),
        BuiltinMemberSpec("initialAccountBufferSize", "size_t", "method", (), "initialAccountBufferSize"),
        BuiltinMemberSpec("descriptorCloseBound", "int", "method", (), "descriptorCloseBound"),
        BuiltinMemberSpec("closeDescriptorsForExec", "int", "method", (("int", "bound"),), "closeDescriptorsForExec"),
        BuiltinMemberSpec("configureMaster", "bool", "method", (("int", "fd"),), "configureMaster"),
        BuiltinMemberSpec("pollUntil", "int", "method", (("int", "fd"), ("short", "events"), ("long long", "deadline"), ("int", "maxWaitMillis"),), "pollUntil"),
        BuiltinMemberSpec("writeBytesUntil", "bool", "method", (("int", "fd"), ("char*", "bytes"), ("size_t", "length"), ("long long", "deadline"),), "writeBytesUntil"),
        BuiltinMemberSpec("writeResponseUntil", "bool", "method", (("int", "fd"), ("string", "value"), ("long long", "deadline"),), "writeResponseUntil"),
        BuiltinMemberSpec("passwordInputHidden", "bool", "method", (("int", "fd"),), "passwordInputHidden"),
        BuiltinMemberSpec("answerPasswordPrompts", "bool", "method", (("int", "fd"), ("Vector<string>", "responses"), ("int", "responseCount"), ("long long", "deadline"),), "answerPasswordPrompts"),
        BuiltinMemberSpec("writeResponse", "bool", "method", (("int", "fd"), ("string", "value"),), "writeResponse"),
        BuiltinMemberSpec("killAndReap", "int", "method", (("pid_t", "processId"),), "killAndReap"),
        BuiltinMemberSpec("killPtyAndReap", "int", "method", (("pid_t", "processId"),), "killPtyAndReap"),
        BuiltinMemberSpec("waitForExitUntil", "int", "method", (("pid_t", "processId"), ("long long", "deadline"),), "waitForExitUntil"),
        BuiltinMemberSpec("waitForPtyExitUntil", "int", "method", (("pid_t", "processId"), ("int", "fd"), ("long long", "deadline"),), "waitForPtyExitUntil"),
        BuiltinMemberSpec("change", "bool", "method", (("string", "user"), ("string", "oldPassword"), ("string", "newPassword"),), "change"),
    )),
    ("TerminalClock", (
        BuiltinMemberSpec("milliseconds", "long long", "method", (), "milliseconds"),
        BuiltinMemberSpec("deadlineAfter", "long long", "method", (("int", "milliseconds"),), "deadlineAfter"),
    )),
    ("UnixPamCStringArray", (
        BuiltinMemberSpec("copyEntry", "char*", "method", (("string", "value"),), "copyEntry"),
        BuiltinMemberSpec("freeEntries", "void", "method", (("char**", "values"),), "freeEntries"),
        BuiltinMemberSpec("copyAll", "char**", "method", (("Vector<string>", "values"),), "copyAll"),
    )),
    ("TerminalPasswordInput", (
        BuiltinMemberSpec("configureSignalDescriptor", "bool", "method", (("int", "descriptor"),), "configureSignalDescriptor"),
        BuiltinMemberSpec("ensureSignalPipe", "bool", "method", (), "ensureSignalPipe"),
        BuiltinMemberSpec("drainSignalPipe", "void", "method", (), "drainSignalPipe"),
        BuiltinMemberSpec("setTerminalAttributes", "bool", "method", (("int", "descriptor"), ("struct termios*", "attributes"),), "setTerminalAttributes"),
        BuiltinMemberSpec("readLine", "string", "method", (), "readLine"),
        BuiltinMemberSpec("signalReadDescriptor", "int", "method", (), "signalReadDescriptor"),
        BuiltinMemberSpec("signalWriteDescriptor", "int", "method", (), "signalWriteDescriptor"),
        BuiltinMemberSpec("prompt", "string", "method", (("string", "label"),), "prompt"),
    )),
    ("UnixPasswdPromptExchange", (
        BuiltinMemberSpec("quietIntervalMilliseconds", "int", "method", (), "quietIntervalMilliseconds"),
        BuiltinMemberSpec("pollUntil", "int", "method", (("int", "fd"), ("short", "events"), ("long long", "deadline"), ("int", "maxWaitMillis"),), "pollUntil"),
        BuiltinMemberSpec("passwordInputHidden", "bool", "method", (("int", "fd"),), "passwordInputHidden"),
        BuiltinMemberSpec("safeResponse", "bool", "method", (("string", "value"),), "safeResponse"),
        BuiltinMemberSpec("writeBytesUntil", "bool", "method", (("int", "fd"), ("char*", "bytes"), ("size_t", "length"), ("long long", "deadline"),), "writeBytesUntil"),
        BuiltinMemberSpec("writeResponseUntil", "bool", "method", (("int", "fd"), ("string", "value"), ("long long", "deadline"),), "writeResponseUntil"),
        BuiltinMemberSpec("answer", "bool", "method", (("int", "fd"), ("Vector<string>", "responses"), ("int", "responseCount"), ("long long", "deadline"),), "answer"),
    )),
    ("Toml", (
        BuiltinMemberSpec("unquotedPosition", "int", "method", (("string", "line"), ("char", "target"),), "unquotedPosition"),
        BuiltinMemberSpec("stripInlineComment", "string", "method", (("string", "raw"),), "stripInlineComment"),
        BuiltinMemberSpec("unquote", "string", "method", (("string", "raw"),), "unquote"),
        BuiltinMemberSpec("key", "string", "method", (("string", "line"),), "key"),
        BuiltinMemberSpec("value", "string", "method", (("string", "line"),), "value"),
        BuiltinMemberSpec("sectionName", "string", "method", (("string", "line"),), "sectionName"),
        BuiltinMemberSpec("tableArrayName", "string", "method", (("string", "line"),), "tableArrayName"),
        BuiltinMemberSpec("rootMap", "Map<string, string>", "method", (("string", "content"),), "rootMap"),
        BuiltinMemberSpec("sectionMap", "Map<string, string>", "method", (("string", "content"), ("string", "section"),), "sectionMap"),
        BuiltinMemberSpec("tableArrayBlocks", "Vector<Map<string, string>>", "method", (("string", "content"), ("string", "table"),), "tableArrayBlocks"),
    )),
    ("Html", (
        BuiltinMemberSpec("escape", "string", "method", (("string", "raw"),), "escape"),
    )),
    ("LinuxUiBuilder", (
        BuiltinMemberSpec("html", "HtmlUiBackend", "method", (), "html"),
        BuiltinMemberSpec("native", "NativeUiBackend", "method", (), "native"),
    )),
    ("MacUiBuilder", (
        BuiltinMemberSpec("html", "HtmlUiBackend", "method", (), "html"),
        BuiltinMemberSpec("native", "NativeUiBackend", "method", (), "native"),
    )),
    ("WindowsUiBuilder", (
        BuiltinMemberSpec("html", "HtmlUiBackend", "method", (), "html"),
        BuiltinMemberSpec("native", "NativeUiBackend", "method", (), "native"),
    )),
    ("Ui", (
        BuiltinMemberSpec("node", "UiNode", "method", (("string", "tag"),), "node"),
        BuiltinMemberSpec("text", "UiNode", "method", (("string", "value"),), "text"),
        BuiltinMemberSpec("rawHtml", "UiNode", "method", (("string", "value"),), "rawHtml"),
        BuiltinMemberSpec("div", "UiNode", "method", (), "div"),
        BuiltinMemberSpec("button", "UiNode", "method", (("string", "label"),), "button"),
        BuiltinMemberSpec("input", "UiNode", "method", (("string", "name"), ("string", "value"),), "input"),
        BuiltinMemberSpec("document", "UiDocument", "method", (("string", "title"), ("UiNode", "body"),), "document"),
    )),
    ("NativeUi", (
        BuiltinMemberSpec("applescriptString", "string", "method", (("string", "raw"),), "applescriptString"),
        BuiltinMemberSpec("detect", "NativeUiBackend", "method", (), "detect"),
    )),
    ("UiRuntime", (
        BuiltinMemberSpec("runCommandAsync", "Thread<int>", "method", (("Command", "command"),), "runCommandAsync"),
        BuiltinMemberSpec("notifyAsync", "Thread<int>", "method", (("NativeUiBackend", "backend"), ("string", "title"), ("string", "body"),), "notifyAsync"),
    )),
)

# Built-in free function signatures: name -> (return_type, params)
BUILTIN_FUNCTION_SIGNATURES: tuple[tuple[str, tuple[str, tuple[tuple[str, str], ...]]], ...] = (
    ("println", ("void", (("string", "message"),))),
    ("print", ("void", (("string", "message"),))),
    ("input", ("string", (("string", "prompt"),))),
    ("toString", ("string", (("int", "value"),))),
    ("toInt", ("int", (("string", "value"),))),
    ("toFloat", ("float", (("string", "value"),))),
    ("len", ("int", (("string", "s"),))),
    ("range", ("Vector<int>", (("int", "n"),))),
    ("exit", ("void", (("int", "code"),))),
)