.PHONY: all help build package wheel btrcc btrcc-release-c btrcc-macos-arm64 btrcc-macos-x64 btrcc-linux-x64 btrcc-linux-arm64 \
        btrcc-windows-x64 btrcc-dist test-windows gpu gpu-required gui ast-generate ast-generate-btrc \
        test test-unit test-lsp test-debug test-btrc test-btrc-selfhost test-selfhost bootstrap test-c11 test-generate-goldens \
        generated-check compiler-codegen-generate compiler-codegen-check lint format format-check \
        examples examples-todo examples-game examples-triangle examples-sgd examples-gui bench \
        extension extension-install \
        devcontainer clean

SHELL       := /bin/bash
NIX         := nix develop --command
HOST_AR     := $(if $(filter Darwin,$(shell uname -s)),/usr/bin/ar,ar)
GPU_OBJC    ?= clang
# The repository links wgpu-native, whose WaitAny entry point aborts. Override
# this only when linking a conforming webgpu.h implementation such as Dawn.
GPU_BACKEND_CFLAGS ?= -DBTRC_GPU_WGPU_NATIVE
GPU_THREAD_FLAGS ?= $(if $(filter Windows_NT,$(OS)),,-pthread)
NATIVE_CFLAGS := -std=c11 -Wall -Wextra -Werror -pedantic
PYTEST      := python3 -m pytest
# Self-host fixture compiles are memory-heavy; callers may raise this explicitly.
PYTEST_WORKERS ?= 4
PYTEST_ARGS ?= -x -q -n $(PYTEST_WORKERS)
PYTEST_SERIAL_ARGS ?= -x -q

all: generated-check build gpu gui test lint examples extension ## Build and verify everything

build: generated-check ## Create bin/btrcpy wrapper script
	@mkdir -p bin
	@printf '%s\n' \
		'#!/usr/bin/env python3' \
		'import sys, os' \
		'sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))' \
		'from src.compiler.python.main import main' \
		'main()' > bin/btrcpy
	@chmod +x bin/btrcpy
	@echo "Built bin/btrcpy"

package: generated-check ## Build the Python sdist, then verify it by building its wheel -> dist/
	rm -rf build/lib/ build/bdist.*/ btrc.egg-info/ src/btrc.egg-info/
	rm -f dist/btrc-*.whl dist/btrc-*.tar.gz
	$(NIX) python3 -m build --no-isolation

wheel: generated-check ## Build the installable Python wheel -> dist/
	rm -rf build/lib/ build/bdist.*/ btrc.egg-info/ src/btrc.egg-info/
	rm -f dist/btrc-*.whl dist/btrc-*.tar.gz
	$(NIX) python3 -m build --wheel --no-isolation

# --- Self-hosted compiler (btrcc) native + cross builds ----------------------
# btrcc is btrc source -> transpiled to C by btrcpy -> compiled by a C toolchain.
# The transpile runs once into dist/btrcc.c; each target compiles that C. Cross
# builds use `zig cc` (one host -> many OS/arch). Release targets place private
# raw binaries under build/btrcc/, then publish relocatable bundles containing
# bin/btrcc plus share/btrc/{language,stdlib} and deterministic archives.
ZIG     := $(NIX) zig
BTRCC_C := dist/btrcc.c
BTRCC_BUILD_ROOT := build/btrcc
BTRCC_BUNDLER := $(NIX) python3 -m src.compiler.python.main bundle
# dist/btrcc.c is generated by the Python compiler from the self-hosted
# compiler plus imported stdlib/spec inputs. Keep each source category explicit
# so a change cannot silently reuse stale generated C.
PYTHON_AST := src/compiler/python/syntax/ast/generated.py
BTRC_AST := src/compiler/btrc/generated/ast/node.btrc
BTRCC_GENERATED_AST := $(PYTHON_AST) $(BTRC_AST)
BTRCC_BOOTSTRAP_SOURCES := $(filter-out src/compiler/python/syntax/ast/generated.py,$(shell find src/compiler/python -type f -name '*.py' ! -path '*/tests/*' -print | LC_ALL=C sort))
BTRCC_SELFHOST_SOURCES := $(filter-out src/compiler/btrc/generated/ast/node.btrc,$(shell find src/compiler/btrc -type f -name '*.btrc' -print | LC_ALL=C sort))
BTRCC_STDLIB_SOURCES := $(shell find src/stdlib -type f -name '*.btrc' -print | LC_ALL=C sort)
BTRCC_LANGUAGE_SPECS := $(shell find src/language -type f \( -name '*.ebnf' -o -name '*.asdl' \) -print | LC_ALL=C sort)
BTRCC_RUNTIME_SPECS := $(shell find src/runtime/c -type f \( -name '*.c' -o -name '*.h' -o -name '*.toml' \) -print | LC_ALL=C sort)
BTRCC_CODEGEN_SOURCES := $(shell find tools/compiler_codegen -type f -name '*.py' -print | LC_ALL=C sort)
BTRCC_INPUTS := $(BTRCC_BOOTSTRAP_SOURCES) $(BTRCC_SELFHOST_SOURCES) \
	$(BTRCC_STDLIB_SOURCES) $(BTRCC_LANGUAGE_SPECS) $(BTRCC_RUNTIME_SPECS) \
	$(BTRCC_CODEGEN_SOURCES) $(BTRCC_GENERATED_AST)
# Windows-only compat layer (POSIX builds never see it): shim headers for the
# handful of POSIX includes MinGW-w64 omits (found via -I) plus a force-included
# header that supplies the few missing symbols and safe filesystem seams. See
# src/stdlib/win/README.md. Real Win32 backends for terminal/process/socket are
# a Milestone-2 follow-up; today these orphan APIs are DCE'd out of btrcc.
WIN_COMPAT := -I src/stdlib/win -include src/stdlib/win/btrc_win_compat.h

$(BTRCC_C): $(BTRCC_INPUTS) | generated-check
	@mkdir -p dist
	$(NIX) python3 -m src.compiler.python.main src/compiler/btrc/btrcc_main.btrc --strict-imports --no-cache -o $(BTRCC_C)

btrcc-release-c: generated-check
	$(MAKE) --no-print-directory $(BTRCC_C)

btrcc: btrcc-release-c ## Build the self-hosted compiler for THIS machine -> bin/btrcc
	@mkdir -p bin
	$(NIX) cc $(NATIVE_CFLAGS) -O2 $(BTRCC_C) -o bin/btrcc -lm -lpthread
	@echo "Built bin/btrcc (native $$(uname -s) $$(uname -m))"

btrcc-macos-arm64: btrcc-release-c ## Build relocatable btrcc bundle for macOS arm64 -> dist/
	@mkdir -p $(BTRCC_BUILD_ROOT)/macos-arm64 dist
	@if [ -e dist/btrcc-macos-arm64 ] && [ ! -d dist/btrcc-macos-arm64 ]; then rm -f dist/btrcc-macos-arm64; fi
	$(ZIG) cc -target aarch64-macos $(NATIVE_CFLAGS) -O2 $(BTRCC_C) -o $(BTRCC_BUILD_ROOT)/macos-arm64/btrcc -lm
	$(BTRCC_BUNDLER) --binary $(BTRCC_BUILD_ROOT)/macos-arm64/btrcc --target macos-arm64 --output-dir dist --source-root .

btrcc-macos-x64: btrcc-release-c ## Build relocatable btrcc bundle for macOS x86_64 -> dist/
	@mkdir -p $(BTRCC_BUILD_ROOT)/macos-x64 dist
	@if [ -e dist/btrcc-macos-x64 ] && [ ! -d dist/btrcc-macos-x64 ]; then rm -f dist/btrcc-macos-x64; fi
	$(ZIG) cc -target x86_64-macos $(NATIVE_CFLAGS) -O2 $(BTRCC_C) -o $(BTRCC_BUILD_ROOT)/macos-x64/btrcc -lm
	$(BTRCC_BUNDLER) --binary $(BTRCC_BUILD_ROOT)/macos-x64/btrcc --target macos-x64 --output-dir dist --source-root .

btrcc-linux-x64: btrcc-release-c ## Build relocatable btrcc bundle for Linux x86_64 -> dist/
	@mkdir -p $(BTRCC_BUILD_ROOT)/linux-x64 dist
	@if [ -e dist/btrcc-linux-x64 ] && [ ! -d dist/btrcc-linux-x64 ]; then rm -f dist/btrcc-linux-x64; fi
	$(ZIG) cc -target x86_64-linux-gnu $(NATIVE_CFLAGS) -O2 $(BTRCC_C) -o $(BTRCC_BUILD_ROOT)/linux-x64/btrcc -lm
	$(BTRCC_BUNDLER) --binary $(BTRCC_BUILD_ROOT)/linux-x64/btrcc --target linux-x64 --output-dir dist --source-root .

btrcc-linux-arm64: btrcc-release-c ## Build relocatable btrcc bundle for Linux arm64 -> dist/
	@mkdir -p $(BTRCC_BUILD_ROOT)/linux-arm64 dist
	@if [ -e dist/btrcc-linux-arm64 ] && [ ! -d dist/btrcc-linux-arm64 ]; then rm -f dist/btrcc-linux-arm64; fi
	$(ZIG) cc -target aarch64-linux-gnu $(NATIVE_CFLAGS) -O2 $(BTRCC_C) -o $(BTRCC_BUILD_ROOT)/linux-arm64/btrcc -lm
	$(BTRCC_BUNDLER) --binary $(BTRCC_BUILD_ROOT)/linux-arm64/btrcc --target linux-arm64 --output-dir dist --source-root .

btrcc-windows-x64: btrcc-release-c ## Build relocatable btrcc bundle for Windows x86_64 -> dist/
	@mkdir -p $(BTRCC_BUILD_ROOT)/windows-x64 dist
	@rm -f dist/btrcc-windows-x64.exe
	@if [ -e dist/btrcc-windows-x64 ] && [ ! -d dist/btrcc-windows-x64 ]; then rm -f dist/btrcc-windows-x64; fi
	$(ZIG) cc -target x86_64-windows-gnu $(NATIVE_CFLAGS) -O2 $(WIN_COMPAT) $(BTRCC_C) -o $(BTRCC_BUILD_ROOT)/windows-x64/btrcc.exe -lm
	$(BTRCC_BUNDLER) --binary $(BTRCC_BUILD_ROOT)/windows-x64/btrcc.exe --target windows-x64 --output-dir dist --source-root .

btrcc-dist: btrcc-macos-arm64 btrcc-macos-x64 btrcc-linux-x64 btrcc-linux-arm64 btrcc-windows-x64 ## Build all relocatable btrcc distributions -> dist/
	@echo "Relocatable btrcc archives:"; find dist -maxdepth 1 -type f \( -name 'btrcc-*.tar.gz' -o -name 'btrcc-*.zip' -o -name 'btrcc-*.sha256' \) -print | LC_ALL=C sort

# Lightweight Windows test env: build the btrcc bundle + a sample btrc program
# to .exe (proves the whole Windows toolchain path end-to-end on ANY host), then run
# the sample under wine if available (Linux/CI), skipping execution gracefully
# elsewhere (e.g. Apple Silicon, where x86_64 wine isn't readily available).
WIN_SAMPLE := src/tests/strings/test_braces_in_code_gen.btrc
WIN_PATH_SAMPLE := src/tests/stdlib/test_stdlib_path_windows_lexical.btrc
test-windows: btrcc-windows-x64 ## Build Windows btrcc bundle + sample; run sample under wine if present
	@mkdir -p dist
	@echo "==> cross-compiling sample btrc program to a Windows .exe"
	$(NIX) python3 -m src.compiler.python.main $(WIN_SAMPLE) --no-cache -o dist/win_sample.c
	$(ZIG) cc -target x86_64-windows-gnu $(NATIVE_CFLAGS) -O2 $(WIN_COMPAT) dist/win_sample.c -o dist/win_sample.exe -lm
	@echo "    built dist/win_sample.exe"
	$(NIX) python3 -m src.compiler.python.main $(WIN_PATH_SAMPLE) --no-cache -o dist/win_paths.c
	$(ZIG) cc -target x86_64-windows-gnu $(NATIVE_CFLAGS) -O2 $(WIN_COMPAT) dist/win_paths.c -o dist/win_paths.exe -lm
	@echo "    built dist/win_paths.exe"
	@if command -v wine64 >/dev/null 2>&1; then WINE=wine64; \
	elif command -v wine >/dev/null 2>&1; then WINE=wine; else WINE=; fi; \
	if [ -n "$$WINE" ]; then \
	  echo "==> running sample under $$WINE"; \
	  out=$$($$WINE dist/win_sample.exe 2>/dev/null); echo "    $$out"; \
	  paths=$$($$WINE dist/win_paths.exe 2>/dev/null); echo "    $$paths"; \
	  echo "$$out" | grep -q "^PASS:" && echo "$$paths" | grep -q "^PASS:" \
	    && echo "PASS: test-windows (ran on Windows via $$WINE)" \
	    || { echo "FAIL: test-windows (unexpected sample output)"; exit 1; }; \
	else \
	  echo "==> wine not available; cross-compile succeeded (execution skipped)"; \
	  echo "SKIP: test-windows execution (install wine, or run on Windows/CI to execute)"; \
	fi

gpu: ## Build GPU runtime library (skips if deps missing)
	@$(NIX) bash -c '\
		D=src/stdlib/gpu && O=build/stdlib/gpu && \
		mkdir -p "$$O" && \
		rm -f "$$O/libbtrc_gpu.a" && \
		probe_ok=1 && \
		for source in btrc_gpu.c btrc_gpu_async.c btrc_gpu_surface.c; do \
			$(CC) $$GPU_CFLAGS $(GPU_BACKEND_CFLAGS) -std=c11 -I"$$D" \
				-E "$$D/$$source" -o /dev/null 2>/dev/null || probe_ok=0; \
		done && \
		if [ "$$(uname -s)" = Darwin ]; then \
			$(GPU_OBJC) $$GPU_CFLAGS -x objective-c -I"$$D" \
				-E "$$D/btrc_gpu_surface_macos.m" -o /dev/null 2>/dev/null || probe_ok=0; \
		fi && \
		if [ "$$probe_ok" -ne 1 ]; then \
			echo "GPU runtime skipped (missing windowing/WebGPU headers)"; exit 0; \
		fi && \
		$(CC) $$GPU_CFLAGS $(GPU_BACKEND_CFLAGS) $(GPU_THREAD_FLAGS) $(NATIVE_CFLAGS) -I"$$D" -O2 -c "$$D/btrc_gpu.c" -o "$$O/btrc_gpu.o" && \
		$(CC) $$GPU_CFLAGS $(GPU_BACKEND_CFLAGS) $(NATIVE_CFLAGS) -I"$$D" -O2 -c "$$D/btrc_gpu_async.c" -o "$$O/btrc_gpu_async.o" && \
		$(CC) $$GPU_CFLAGS $(NATIVE_CFLAGS) -I"$$D" -O2 -c "$$D/btrc_gpu_surface.c" -o "$$O/btrc_gpu_surface.o" && \
		objects="$$O/btrc_gpu.o $$O/btrc_gpu_async.o $$O/btrc_gpu_surface.o" && \
		if [ "$$(uname -s)" = Darwin ]; then \
			$(GPU_OBJC) $$GPU_CFLAGS $(NATIVE_CFLAGS) -x objective-c -I"$$D" -O2 \
				-c "$$D/btrc_gpu_surface_macos.m" -o "$$O/btrc_gpu_surface_macos.o" && \
			objects="$$objects $$O/btrc_gpu_surface_macos.o"; \
		fi && \
		$(HOST_AR) rcs "$$O/libbtrc_gpu.a" $$objects && \
		$(HOST_AR) t "$$O/libbtrc_gpu.a" | grep -q "btrc_gpu_async\\.o$$" && \
		$(HOST_AR) t "$$O/libbtrc_gpu.a" | grep -q "btrc_gpu_surface\\.o$$" && \
		echo "Built: $$O/libbtrc_gpu.a"'

gpu-required: gpu ## Build GPU runtime library; fail when production dependencies are missing
	@$(NIX) bash -c 'archive=build/stdlib/gpu/libbtrc_gpu.a; \
		test -f "$$archive" || { \
			echo "GPU runtime is required for production tests; install the WebGPU and GLFW development dependencies." >&2; \
			exit 1; \
		}; \
		$(HOST_AR) t "$$archive" | grep -q "btrc_gpu_async\\.o$$" && \
		$(HOST_AR) t "$$archive" | grep -q "btrc_gpu_surface\\.o$$"'

gui: ## Build GUI runtime (software renderer always; window backend needs GLFW)
	@$(NIX) bash -c '\
		D=src/stdlib/gui && O=build/stdlib/gui && mkdir -p "$$O" && \
		archive="$$O/libbtrc_gui.a" && object="$$O/btrc_gui.o" && \
		rm -f "$$archive" "$$object" && \
		trap "rm -f \"$$archive\" \"$$object\"" EXIT && \
		$(CC) $(NATIVE_CFLAGS) -O2 -c "$$D/btrc_gui.c" -o "$$object" && \
		$(HOST_AR) rcs "$$archive" "$$object" && \
		trap - EXIT && \
		echo "Built: $$archive (software renderer)"'
	@$(NIX) bash -c '\
		D=src/stdlib/gui && O=build/stdlib/gui && mkdir -p "$$O" && \
		archive="$$O/libbtrc_gui_window.a" && object="$$O/btrc_gui_window.o" && \
		rm -f "$$archive" "$$object" && \
		trap "rm -f \"$$archive\" \"$$object\"" EXIT && \
		if ! $(CC) $$GPU_CFLAGS -std=c11 -DGL_SILENCE_DEPRECATION -I"$$D" -E "$$D/btrc_gui_window.c" -o /dev/null 2>/dev/null; then \
			echo "GUI window backend skipped (missing GLFW/GL headers)"; exit 0; \
		fi && \
		$(CC) $$GPU_CFLAGS $(NATIVE_CFLAGS) -DGL_SILENCE_DEPRECATION -I"$$D" -O2 -c "$$D/btrc_gui_window.c" -o "$$object" && \
		$(HOST_AR) rcs "$$archive" "$$object" && \
		trap - EXIT && \
		echo "Built: $$archive (GLFW window backend)"'
	@$(NIX) bash -c '\
		D=src/stdlib/gui && O=build/stdlib/gui && mkdir -p "$$O" && \
		archive="$$O/libbtrc_gui_font.a" && object="$$O/btrc_gui_font.o" && \
		rm -f "$$archive" "$$object" && \
		trap "rm -f \"$$archive\" \"$$object\"" EXIT && \
		if ! $(CC) $$FONT_CFLAGS -std=c11 -I"$$D" -E "$$D/btrc_gui_font.c" -o /dev/null 2>/dev/null; then \
			echo "GUI font backend skipped (missing FreeType headers)"; exit 0; \
		fi && \
		$(CC) $$FONT_CFLAGS $(NATIVE_CFLAGS) -I"$$D" -O2 -c "$$D/btrc_gui_font.c" -o "$$object" && \
		$(HOST_AR) rcs "$$archive" "$$object" && \
		trap - EXIT && \
		echo "Built: $$archive (FreeType scalable fonts)"'

ast-generate: compiler-codegen-generate ## Regenerate both AST catalogs through the unified owner

ast-generate-btrc: compiler-codegen-generate ## Regenerate both AST catalogs through the unified owner

# ─── Test ────────────────────────────────────────────────────────────────────

test: generated-check gpu-required ## Run everything: unit + LSP + debugger + language corpus on BOTH compilers
	$(NIX) $(PYTEST) src/tests/ \
		--ignore=src/tests/btrc/test_bootstrap.py $(PYTEST_ARGS)
	$(NIX) $(PYTEST) src/tests/btrc/test_bootstrap.py $(PYTEST_SERIAL_ARGS)

test-unit: generated-check ## Run Python reference-compiler unit tests (lexer, parser, analyzer, codegen)
	$(NIX) $(PYTEST) src/tests/python/ $(PYTEST_ARGS)

test-lsp: generated-check ## Run the editor/LSP server tests (reuses the compiler)
	$(NIX) $(PYTEST) src/tests/lsp/ $(PYTEST_ARGS)

test-debug: generated-check ## Run the debugger (DAP adapter) tests (needs lldb + a C compiler)
	$(NIX) $(PYTEST) src/tests/debug/ $(PYTEST_ARGS)

test-selfhost: generated-check ## Verify the self-hosted lexer is byte-identical to btrcpy
	$(NIX) python3 -m tools.compiler_codegen.main verify-lexer

test-btrc: generated-check ## Language corpus through the Python reference compiler (fast)
	$(NIX) $(PYTEST) src/tests/runner.py --compilers=python $(PYTEST_ARGS)

test-btrc-selfhost: generated-check ## Language corpus through the self-hosted compiler (btrcc) + btrc-specific tests
	$(NIX) $(PYTEST) src/tests/runner.py --compilers=btrc src/tests/btrc/ \
		--ignore=src/tests/btrc/test_bootstrap.py $(PYTEST_ARGS)

bootstrap: generated-check ## Prove the self-hosted compiler reproduces itself bit-for-bit (fixed point)
	$(NIX) $(PYTEST) src/tests/btrc/test_bootstrap.py -v $(PYTEST_SERIAL_ARGS)

test-c11: generated-check gpu-required btrcc ## Strict C11: both compilers with gcc + clang at -O0 through -O3
	@$(NIX) bash -c '\
		for cc in gcc clang; do \
			for opt in O0 O1 O2 O3; do \
				echo "=== $$cc -std=c11 -$$opt ===" && \
				BTRC_TEST_BTRCC="$(abspath bin/btrcc)" BTRC_CC=$$cc \
					BTRC_CFLAGS="-std=c11 -pedantic-errors -Wall -Wextra -Werror -$$opt" \
					$(PYTEST) src/tests/runner.py --compilers=python,btrc $(PYTEST_ARGS) || exit 1; \
			done; \
		done && \
		echo "All C11 compliance tests passed (gcc + clang, -O0 through -O3)."'

test-generate-goldens: generated-check ## Regenerate golden .stdout files
	$(NIX) python3 src/tests/generate_expected.py

compiler-codegen-generate: ## Regenerate compiler sources from shared specifications
	$(NIX) python3 -m tools.compiler_codegen.main generate

compiler-codegen-check: ## Check shared-spec generated compiler sources
	$(NIX) python3 -m tools.compiler_codegen.main check

generated-check: compiler-codegen-check ## Check every committed generated source without modifying it

lint: generated-check ## Run generated-policy checks and ruff linter
	$(NIX) ruff check src/

format: ## Format with ruff
	$(NIX) ruff format src/

format-check: ## Check formatting (CI)
	$(NIX) ruff format --check src/

# ─── Examples ────────────────────────────────────────────────────────────────

examples: generated-check gpu-required ## Build and run all examples
	$(NIX) $(MAKE) -C examples all

examples-todo: generated-check ## Build the todo example
	$(NIX) $(MAKE) -C examples todo

examples-game: generated-check gpu-required ## Build the 3D engine game
	$(NIX) $(MAKE) -C examples game

examples-triangle: generated-check gpu-required ## Build the GPU triangle example
	$(NIX) $(MAKE) -C examples triangle

examples-sgd: generated-check gpu-required ## Build the GPU SGD example
	$(NIX) $(MAKE) -C examples sgd

examples-gui: generated-check ## Build + run the headless GUI example
	$(NIX) $(MAKE) -C examples gui

bench: generated-check ## Build + run the benchmark suite (times transpile + compile + run)
	$(NIX) $(MAKE) -C bench

# ─── VSCode Extension ───────────────────────────────────────────────────────

extension: generated-check ## Package VSCode extension (.vsix)
	$(NIX) bash -c 'set -euo pipefail; \
		export BTRC_PACKAGING_PYTHON="$$(command -v python3)"; \
		node src/devex/vscode/packaging/prepare.js; \
		cd build/devex/vscode && npm ci && npm test && npm run package'

extension-install: extension ## Install VSCode extension (dev)
	$(NIX) bash -c 'set -euo pipefail; \
		code --install-extension dist/btrc.vsix --force'

# ─── Infrastructure ─────────────────────────────────────────────────────────

devcontainer: ## Generate .devcontainer/ and build image
	@set -e; \
	mkdir -p .devcontainer; \
	nix build .#devcontainer --out-link .devcontainer/.result; \
	install -m 644 .devcontainer/.result/devcontainer.json .devcontainer/devcontainer.json; \
	install -m 644 .devcontainer/.result/Containerfile .devcontainer/Containerfile; \
	install -m 644 .devcontainer/.result/bashrc .devcontainer/bashrc; \
	install -m 755 .devcontainer/.result/host.sh .devcontainer/host.sh; \
	rm -f .devcontainer/.result; \
	podman build -f .devcontainer/Containerfile -t btrc-devcontainer:latest .; \
	echo "Done. Image: btrc-devcontainer:latest"

clean: ## Remove all build artifacts
	rm -rf bin/ dist/ .btrc-cache/ .devcontainer/
	rm -rf .pytest_cache/ .ruff_cache/ htmlcov/ .coverage .coverage.* coverage.json coverage.xml
	rm -rf build/generated/ build/devex/vscode/ build/stdlib/ build/out/ build/lib/ build/bdist.*/ build/btrcc/ build/temp.*/
	rm -rf btrc.egg-info/ src/btrc.egg-info/
	find src examples bench -type d \( -name __pycache__ -o -name .pytest_cache \) -prune -exec rm -rf {} +
	find src examples bench -type d -name '*.dSYM' -prune -exec rm -rf {} +
	find src examples bench -type f \( -name '*.pyc' -o -name '*.o' \) -delete
	find src/tests -type f -name 'test_*.c' -delete
	$(MAKE) -C examples clean 2>/dev/null || true
	$(MAKE) -C bench clean 2>/dev/null || true

help:
	@grep -E '^[a-zA-Z0-9_-]+:.*?## .*$$' $(MAKEFILE_LIST) | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-26s\033[0m %s\n", $$1, $$2}'
