manifest-version = 1

[package]
name = "btrc_stdlib_http"
exports = ["HTTP", "HTTPClient", "HTTPFraming", "HTTPRequest", "HTTPResponse", "HTTPResponseHeaders", "HTTPServer", "HTTPSocket", "HTTPStatus", "HTTPUrl"]
