"""End-to-end proof that the actual self-hosted distribution is relocatable."""

from __future__ import annotations

import os
import shlex
import shutil
import subprocess
from pathlib import Path

import pytest

from src.compiler.python.artifacts.archive import TargetCatalog
from src.compiler.python.artifacts.selfhost import SelfhostBundleBuilder

pytest_plugins = ("src.tests.btrc.test_semantic_validation",)

REPO = Path(__file__).resolve().parents[3]
CC = shlex.split(os.environ.get("BTRC_CC", "cc"))

pytestmark = pytest.mark.skipif(
    not CC or shutil.which(CC[0]) is None,
    reason="needs a C compiler",
)


def _without_btrc_home() -> dict[str, str]:
    environment = dict(os.environ)
    environment.pop("BTRC_HOME", None)
    return environment


def _run(
    command: list[str],
    *,
    cwd: Path,
    env: dict[str, str] | None = None,
    timeout: int = 120,
) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        command,
        cwd=cwd,
        env=env,
        capture_output=True,
        text=True,
        timeout=timeout,
    )


def test_actual_bundle_compiles_and_runs_stdlib_program_from_unrelated_cwd(
    semantic_btrcc: Path,
    tmp_path: Path,
) -> None:
    targets = TargetCatalog()
    target = targets.host_target()
    distribution = SelfhostBundleBuilder().build(
        binary=semantic_btrcc,
        target=target,
        output_dir=tmp_path / "dist",
        source_root=REPO,
        epoch=0,
    )
    compiler = distribution.bundle / targets.spec(target).executable
    data_root = distribution.bundle / "share/btrc"
    unrelated = tmp_path / "unrelated-working-directory"
    unrelated.mkdir()
    environment = _without_btrc_home()

    inspected = _run([str(compiler), "--stdlib-dir"], cwd=unrelated, env=environment)
    assert inspected.returncode == 0, inspected.stderr
    assert inspected.stdout == f"{data_root.resolve() / 'stdlib'}\n"

    source = tmp_path / "stdlib-program.btrc"
    generated = tmp_path / "stdlib-program.c"
    binary = tmp_path / "stdlib-program"
    source.write_text(
        "import Library.Vector;\n"
        "\n"
        "int main() {\n"
        '    Vector<string> values = ["relocated", "compiler"];\n'
        '    print(values.join("-"));\n'
        "    return 0;\n"
        "}\n",
        encoding="utf-8",
    )
    compiled = _run([str(compiler), str(source)], cwd=unrelated, env=environment)
    assert compiled.returncode == 0, compiled.stderr
    assert compiled.stdout.startswith("/* Generated by btrc */\n")
    assert "#include <stdio.h>" in compiled.stdout
    generated.write_text(compiled.stdout, encoding="utf-8", newline="\n")

    native = _run(
        [
            *CC,
            "-std=c11",
            "-pedantic-errors",
            "-Wall",
            "-Wextra",
            "-Werror",
            str(generated),
            "-o",
            str(binary),
            "-lm",
            "-lpthread",
        ],
        cwd=unrelated,
        timeout=300,
    )
    assert native.returncode == 0, native.stderr
    executed = _run([str(binary)], cwd=unrelated)
    assert executed.returncode == 0, executed.stderr
    assert executed.stdout == "relocated-compiler\n"

    header_source = tmp_path / "native-header-program.btrc"
    header_generated = tmp_path / "native-header-program.c"
    header_object = tmp_path / "native-header-program.o"
    header_source.write_text(
        "import Library.BackgroundJobs;\n"
        "int main() {\n"
        "    BackgroundJobCancellation cancellation = BackgroundJobCancellation();\n"
        "    return cancellation.requested() ? 1 : 0;\n"
        "}\n",
        encoding="utf-8",
    )
    # Native header bindings need an explicit target on the self-hosted
    # compiler even without a project manifest.
    header_compiled = _run([str(compiler), "--target", target, str(header_source)], cwd=unrelated, env=environment)
    assert header_compiled.returncode == 0, header_compiled.stderr
    # The BackgroundJobs binding header is included from the bundle's own data
    # root, so the generated C compiles without any repository checkout present.
    assert f'#include "{data_root.resolve() / "stdlib/BackgroundJobs/NativeThreads.h"}"' in header_compiled.stdout
    header_generated.write_text(header_compiled.stdout, encoding="utf-8", newline="\n")
    header_check = _run(
        [
            *CC,
            "-std=c11",
            "-pedantic-errors",
            "-Wall",
            "-Wextra",
            "-Werror",
            "-I",
            str(data_root / "stdlib/BackgroundJobs"),
            "-c",
            str(header_generated),
            "-o",
            str(header_object),
        ],
        cwd=unrelated,
        timeout=300,
    )
    assert header_check.returncode == 0, header_check.stderr
    assert header_object.is_file()
