"""End-to-end proof that the actual self-hosted distribution is relocatable."""

from __future__ import annotations

import os
import shlex
import shutil
import subprocess
from pathlib import Path

import pytest

from src.compiler.python.artifacts.selfhost_bundle.builder import BundleBuilder
from src.compiler.python.btrcc_target_binary import host_target, target_spec

pytest_plugins = ("src.tests.btrc.test_semantic_validation",)

REPO = Path(__file__).resolve().parents[3]
CC = shlex.split(os.environ.get("BTRC_CC", "cc"))

pytestmark = pytest.mark.skipif(
    not CC or shutil.which(CC[0]) is None,
    reason="needs a C compiler",
)


def _without_btrc_home() -> dict[str, str]:
    environment = dict(os.environ)
    environment.pop("BTRC_HOME", None)
    return environment


def _run(
    command: list[str],
    *,
    cwd: Path,
    env: dict[str, str] | None = None,
    timeout: int = 120,
) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        command,
        cwd=cwd,
        env=env,
        capture_output=True,
        text=True,
        timeout=timeout,
    )


def test_actual_bundle_compiles_and_runs_stdlib_program_from_unrelated_cwd(
    semantic_btrcc: Path,
    tmp_path: Path,
) -> None:
    target = host_target()
    distribution = BundleBuilder().build(
        binary=semantic_btrcc,
        target=target,
        output_dir=tmp_path / "dist",
        source_root=REPO,
        epoch=0,
    )
    compiler = distribution.bundle / target_spec(target).executable
    data_root = distribution.bundle / "share/btrc"
    unrelated = tmp_path / "unrelated-working-directory"
    unrelated.mkdir()
    environment = _without_btrc_home()

    inspected = _run([str(compiler), "--stdlib-dir"], cwd=unrelated, env=environment)
    assert inspected.returncode == 0, inspected.stderr
    assert inspected.stdout == f"{data_root.resolve() / 'stdlib'}\n"

    source = tmp_path / "stdlib-program.btrc"
    generated = tmp_path / "stdlib-program.c"
    binary = tmp_path / "stdlib-program"
    source.write_text(
        "int main() {\n"
        '    Vector<string> values = ["relocated", "compiler"];\n'
        '    print(values.join("-"));\n'
        "    return 0;\n"
        "}\n",
        encoding="utf-8",
    )
    compiled = _run([str(compiler), str(source)], cwd=unrelated, env=environment)
    assert compiled.returncode == 0, compiled.stderr
    assert compiled.stdout.startswith("/* Generated by btrc */\n")
    assert "#include <stdio.h>" in compiled.stdout
    generated.write_text(compiled.stdout, encoding="utf-8", newline="\n")

    native = _run(
        [
            *CC,
            "-std=c11",
            "-pedantic-errors",
            "-Wall",
            "-Wextra",
            "-Werror",
            str(generated),
            "-o",
            str(binary),
            "-lm",
            "-lpthread",
        ],
        cwd=unrelated,
        timeout=300,
    )
    assert native.returncode == 0, native.stderr
    executed = _run([str(binary)], cwd=unrelated)
    assert executed.returncode == 0, executed.stderr
    assert executed.stdout == "relocated-compiler\n"

    gui_source = tmp_path / "gui-header-program.btrc"
    gui_generated = tmp_path / "gui-header-program.c"
    gui_object = tmp_path / "gui-header-program.o"
    gui_source.write_text(
        '#include "gui/gui.btrc"\n'
        "int main() {\n"
        "    Surface surface = Surface(2, 2);\n"
        "    return surface.width() == 2 ? 0 : 1;\n"
        "}\n",
        encoding="utf-8",
    )
    gui_compiled = _run([str(compiler), str(gui_source)], cwd=unrelated, env=environment)
    assert gui_compiled.returncode == 0, gui_compiled.stderr
    assert "#include <btrc_gui.h>" in gui_compiled.stdout
    gui_generated.write_text(gui_compiled.stdout, encoding="utf-8", newline="\n")
    header_check = _run(
        [
            *CC,
            "-std=c11",
            "-pedantic-errors",
            "-Wall",
            "-Wextra",
            "-Werror",
            "-I",
            str(data_root / "stdlib/gui"),
            "-c",
            str(gui_generated),
            "-o",
            str(gui_object),
        ],
        cwd=unrelated,
        timeout=300,
    )
    assert header_check.returncode == 0, header_check.stderr
    assert gui_object.is_file()
