"""C code emitter for the btrc compiler.

Walks an IR tree and serializes it to C text. This is intentionally simple --
all lowering (class layout, generics, method-to-function, etc.) is done
during IR generation. The emitter just formats.
"""

from __future__ import annotations

from .emitter_archive import _ArchiveEmitterMixin
from .emitter_debug import _DebugEmitterMixin
from .emitter_exprs import _ExprEmitterMixin
from .emitter_gpu import _GpuEmitterMixin
from .emitter_preprocessor import _PreprocessorEmitterMixin
from .emitter_stmts import _StmtEmitterMixin
from .emitter_types import _TypeEmitterMixin
from .nodes import IRFunctionDef, IRMacroDef, IRModule


class CEmitter(
    _ArchiveEmitterMixin,
    _DebugEmitterMixin,
    _StmtEmitterMixin,
    _TypeEmitterMixin,
    _PreprocessorEmitterMixin,
    _GpuEmitterMixin,
    _ExprEmitterMixin,
):
    """Emits C source text from an IRModule."""

    def __init__(self):
        self._lines: list[str] = []
        self._indent: int = 0
        self._module = None  # set by emit(); archive header/impl paths leave None
        self._dbg_enabled = False  # stamp #line on each content line (in func bodies)
        self._dbg_loc = None  # current (btrc_file, line) or None for .c-mapped

    def emit(self, module: IRModule) -> str:
        """Emit the entire IR module as C source text."""
        module.validate_declarations()
        self._lines = []
        self._indent = 0
        self._module = module

        self._line("/* Generated by btrc */")

        # Reserve the preprocessor slot. In freestanding mode whether btrc_rt.h is
        # needed depends on what the body actually references (e.g. print ->
        # printf is emitted directly, registering no helper), so the prologue is
        # filled in at the end once the whole unit is known.
        preprocessor_slot = len(self._lines)

        # Runtime helpers
        for helper in module.helper_decls:
            self._raw(helper.c_source)
            self._line("")

        # Type forwards precede the module's already-planned heterogeneous type
        # declarations. Ordinary function declarations follow complete types.
        for declaration in module.struct_forwards:
            self._emit_struct_forward(declaration)
        if module.struct_forwards:
            self._line("")

        for declaration in module.ordered_type_declarations:
            self._emit_type_declaration(declaration)

        for declaration in module.function_decls:
            self._emit_function_decl(declaration)
        if module.function_decls:
            self._line("")

        # Global variables
        for declaration in module.global_decls:
            self._emit_global_decl(declaration)
        if module.global_decls:
            self._line("")

        # GPU kernel WGSL string constants
        for kernel in module.gpu_kernels:
            self._emit_gpu_kernel(kernel)

        # Function definitions
        for func in module.function_defs:
            self._emit_function(func)

        # Fill in the reserved include slot now that the body is complete.
        preprocessor_lines = self._build_preprocessor_lines(module)
        self._lines[preprocessor_slot:preprocessor_slot] = preprocessor_lines

        # Resolve #line-reset placeholders now that all line positions are final.
        if module.debug:
            self._fix_cline_resets()

        return "\n".join(self._lines) + "\n"

    def _build_preprocessor_lines(
        self,
        module: IRModule,
    ) -> list[str]:
        """Build the translation unit's include prologue.

        Hosted mode lists the system headers the IR gen recorded. Freestanding
        mode emits no system header at all: every runtime dependency is funneled
        through one project-local seam, ``btrc_rt.h`` (the embedder retargets it
        — e.g. malloc->kmalloc, printf->printk). A unit that references no
        runtime symbol (the pure subset) and no explicit ``#include`` gets an
        empty prologue, so its translation unit is fully self-contained.

        Runtime requirements are materialized from structured IR before this
        formatting pass; the emitter never scans generated C to infer them."""
        if module.freestanding:
            if any(
                not isinstance(declaration, IRMacroDef) and declaration.is_system
                for declaration in module.preprocessor_decls
            ):
                raise ValueError("freestanding system includes must be lowered before C emission")
            has_seam = any(
                not isinstance(declaration, IRMacroDef) and declaration.header == "btrc_rt.h"
                for declaration in module.preprocessor_decls
            )
            if module.needs_runtime and not has_seam:
                raise ValueError("freestanding runtime dependency lacks a typed btrc_rt.h include")
            lines = [self._preprocessor_text(declaration) for declaration in module.preprocessor_decls]
            if lines:
                lines.append("")
            return lines
        lines = [self._preprocessor_text(declaration) for declaration in module.preprocessor_decls]
        if lines:
            lines.append("")
        return lines

    # --- Function emission ---

    def _emit_function(self, func: IRFunctionDef):
        self._line(f"{self._function_signature(func)} {{")
        if func.body:
            self._indent += 1
            # Reset #line to the generated .c at function entry so a btrc #line
            # left active by the previous function cannot leak into this one's
            # body (which matters for synthesized functions that emit no markers
            # of their own — otherwise a btrc breakpoint binds to glue code).
            debug = getattr(self._module, "debug", False)
            if debug:
                # Stamp every body line with its btrc location. #line only sets a
                # *starting* line — each subsequent physical line auto-increments,
                # so a btrc statement spanning several C lines (e.g. a Vector
                # literal -> N pushes) would smear across N btrc lines unless each
                # line is restamped. Reset to None first so a synthesized function
                # with no markers (e.g. Point_new) maps to the .c, not stale lines.
                self._dbg_enabled = True
                self._dbg_loc = None
            self._emit_block_contents(func.body)
            self._dbg_enabled = False
            self._indent -= 1
        self._line("}")
        self._line("")

    # --- Output helpers ---
    def _line(self, text: str):
        """Emit physical lines with current indentation."""
        for part in text.split("\n"):
            if part.strip():
                if self._dbg_enabled:
                    self._emit_line_directive()
                self._lines.append("    " * self._indent + part)
            else:
                self._lines.append("")

    def _raw(self, text: str):
        """Emit raw text without indentation adjustment."""
        for line in text.rstrip("\n").split("\n"):
            self._lines.append(line)
