manifest-version = 1

[package]
name = "middle"

[dependencies]
leaf = { path = "../leaf" }

[[native.sources]]
path = "native/middle.cpp"
language = "c++"
standard = "c++17"
modules = ["api"]

[[native.sources]]
path = "native/middle_objc.m"
language = "objective-c"
standard = "c11"
modules = ["api"]
os = ["macos"]

[[native.sources]]
path = "native/middle_objcxx.mm"
language = "objective-c++"
standard = "c++17"
modules = ["api"]
os = ["macos"]

[[native.headers]]
path = "native/middle.h"
modules = ["api"]

[[native.include-directories]]
path = "native"
modules = ["api"]

[[native.defines]]
name = "MIDDLE_ABI"
value = "1"
modules = ["api"]

[[native.frameworks]]
name = "Foundation"
modules = ["api"]
os = ["macos"]

[[native.pkg-config]]
name = "native-package-proof"
modules = ["api"]
os = ["windows"]
