manifest-version = 1

[package]
name = "leaf"

[[native.sources]]
path = "native/leaf.c"
language = "c"
standard = "c11"
modules = ["api"]

[[native.headers]]
path = "native/leaf.h"
modules = ["api"]

[[native.include-directories]]
path = "native"
modules = ["api"]
