"""C code emitter for the btrc compiler.

Walks an IR tree and serializes it to C text. This is intentionally simple --
all lowering (class layout, generics, method-to-function, etc.) is done
during IR generation. The emitter just formats.
"""

from __future__ import annotations

from ..ir.nodes import (
    CType,
    IRAddressOf,
    IRAssign,
    IRBinOp,
    IRBlock,
    IRBreak,
    IRCall,
    IRCast,
    IRCommaExpr,
    IRCompoundLiteral,
    IRContinue,
    IRDeref,
    IRDoWhile,
    IREnumDef,
    IRExpr,
    IRExprStmt,
    IRFieldAccess,
    IRFor,
    IRFunctionDecl,
    IRFunctionDef,
    IRFunctionPointerTypedef,
    IRFunctionRef,
    IRGlobalDecl,
    IRGpuKernel,
    IRIf,
    IRInclude,
    IRIndex,
    IRInitializerList,
    IRLineMarker,
    IRLiteral,
    IRMacroDef,
    IRModule,
    IRReturn,
    IRSizeof,
    IRStmt,
    IRStmtExpr,
    IRStructDef,
    IRStructForward,
    IRSwitch,
    IRTaggedUnionDef,
    IRTernary,
    IRTypedefDef,
    IRUnaryOp,
    IRVar,
    IRVarDecl,
    IRWhile,
)
from ..ir.verifier import IRVerifier
from .wgsl_emitter import WgslEmitter

_INLINE_EXPRESSION_LIMIT = 1000


class CEmitter:
    """Emits C source text from an IRModule."""

    _CLINE_PLACEHOLDER = "@@BTRC_CLINE@@"

    def __init__(self):
        self._lines: list[str] = []
        self._indent: int = 0
        self._module = None  # set by emit(); archive header/impl paths leave None
        self._dbg_enabled = False  # stamp #line on each content line (in func bodies)
        self._dbg_loc = None  # current (btrc_file, line) or None for .c-mapped

    @staticmethod
    def _prepare_module(module: IRModule) -> None:
        """Validate the complete optimizer-prepared IR input."""

        IRVerifier(module).validate()

    def emit(self, module: IRModule) -> str:
        """Emit the entire IR module as C source text."""
        self._prepare_module(module)
        self._lines = []
        self._indent = 0
        self._module = module

        self._line("/* Generated by btrc */")

        # Reserve the preprocessor slot. In freestanding mode whether btrc_rt.h is
        # needed depends on what the body actually references (e.g. print ->
        # printf is emitted directly, registering no helper), so the prologue is
        # filled in at the end once the whole unit is known.
        preprocessor_slot = len(self._lines)

        # Runtime helpers
        for helper in module.helper_decls:
            self._raw(helper.c_source)
            self._line("")

        # Type forwards precede the module's already-planned heterogeneous type
        # declarations. Ordinary function declarations follow complete types.
        for declaration in module.struct_forwards:
            self._emit_struct_forward(declaration)
        if module.struct_forwards:
            self._line("")

        for declaration in module.ordered_type_declarations:
            self._emit_type_declaration(declaration)

        for declaration in module.function_decls:
            self._emit_function_decl(declaration)
        if module.function_decls:
            self._line("")

        # Global variables
        for declaration in module.global_decls:
            self._emit_global_decl(declaration)
        if module.global_decls:
            self._line("")

        # GPU kernel WGSL string constants
        for kernel in module.gpu_kernels:
            self._emit_gpu_kernel(kernel)

        # Function definitions
        for func in module.function_defs:
            self._emit_function(func)

        # Fill in the reserved include slot now that the body is complete.
        preprocessor_lines = self._build_preprocessor_lines(module)
        self._lines[preprocessor_slot:preprocessor_slot] = preprocessor_lines

        # Resolve #line-reset placeholders now that all line positions are final.
        if module.debug:
            self._fix_cline_resets()

        return "\n".join(self._lines) + "\n"

    def emit_header(
        self,
        module: IRModule,
        shared_decls: dict | None = None,
    ) -> str:
        """Emit the public header for a precompiled archive."""

        self._prepare_module(module)
        shared_decls = shared_decls or {}
        self._lines = []
        self._indent = 0

        self._line("#ifndef BTRC_STDLIB_H")
        self._line("#define BTRC_STDLIB_H")
        self._line("")
        self._emit_preprocessor_declarations(module)

        for helper in module.helper_decls:
            self._raw(shared_decls.get(helper.name, helper.c_source))
            self._line("")

        for declaration in module.struct_forwards:
            self._emit_struct_forward(declaration)
        if module.struct_forwards:
            self._line("")

        for declaration in module.ordered_type_declarations:
            self._emit_type_declaration(declaration)

        for declaration in module.function_decls:
            if declaration.is_static:
                continue
            self._emit_function_decl(declaration)
        if any(not declaration.is_static for declaration in module.function_decls):
            self._line("")

        for declaration in module.global_decls:
            if declaration.is_extern:
                self._emit_global_decl(declaration)

        self._line("#endif")
        return "\n".join(self._lines) + "\n"

    def emit_impl(
        self,
        module: IRModule,
        header_include: str,
        shared_names: set | None = None,
    ) -> str:
        """Emit the definition-only implementation for a precompiled archive."""

        self._prepare_module(module)
        shared_names = shared_names or set()
        self._lines = []
        self._indent = 0

        self._line(self._include_text(IRInclude(header=header_include, is_system=False)))
        self._line("")

        private_declarations = [
            declaration
            for declaration in module.function_decls
            if declaration.is_static
        ]
        for declaration in private_declarations:
            self._emit_function_decl(declaration)
        if private_declarations:
            self._line("")

        for helper in module.helper_decls:
            if helper.name in shared_names:
                self._raw(helper.c_source)
                self._line("")

        for declaration in module.global_decls:
            self._emit_global_decl(declaration)
        if module.global_decls:
            self._line("")

        for kernel in module.gpu_kernels:
            self._emit_gpu_kernel(kernel)

        for function in module.function_defs:
            self._emit_function(function)

        return "\n".join(self._lines) + "\n"

    def _build_preprocessor_lines(
        self,
        module: IRModule,
    ) -> list[str]:
        """Build the translation unit's include prologue.

        Hosted mode lists the system headers the IR gen recorded. Freestanding
        mode emits no system header at all: every runtime dependency is funneled
        through one project-local seam, ``btrc_rt.h`` (the embedder retargets it
        — e.g. malloc->kmalloc, printf->printk). A unit that references no
        runtime symbol (the pure subset) and no explicit ``#include`` gets an
        empty prologue, so its translation unit is fully self-contained.

        Runtime requirements are materialized from structured IR before this
        formatting pass; the emitter never scans generated C to infer them."""
        if module.freestanding:
            if any(
                not isinstance(declaration, IRMacroDef) and declaration.is_system
                for declaration in module.preprocessor_decls
            ):
                raise ValueError("freestanding system includes must be lowered before C emission")
            has_seam = any(
                not isinstance(declaration, IRMacroDef) and declaration.header == "btrc_rt.h"
                for declaration in module.preprocessor_decls
            )
            if module.needs_runtime and not has_seam:
                raise ValueError("freestanding runtime dependency lacks a typed btrc_rt.h include")
            lines = [self._preprocessor_text(declaration) for declaration in module.preprocessor_decls]
            if lines:
                lines.append("")
            return lines
        lines = [self._preprocessor_text(declaration) for declaration in module.preprocessor_decls]
        if lines:
            lines.append("")
        return lines

    # --- Function emission ---

    def _emit_function(self, func: IRFunctionDef):
        self._line(f"{self._function_signature(func)} {{")
        if func.body:
            self._indent += 1
            # Reset #line to the generated .c at function entry so a btrc #line
            # left active by the previous function cannot leak into this one's
            # body (which matters for synthesized functions that emit no markers
            # of their own — otherwise a btrc breakpoint binds to glue code).
            debug = getattr(self._module, "debug", False)
            if debug:
                # Stamp every body line with its btrc location. #line only sets a
                # *starting* line — each subsequent physical line auto-increments,
                # so a btrc statement spanning several C lines (e.g. a Vector
                # literal -> N pushes) would smear across N btrc lines unless each
                # line is restamped. Reset to None first so a synthesized function
                # with no markers (e.g. Point_new) maps to the .c, not stale lines.
                self._dbg_enabled = True
                self._dbg_loc = None
            self._emit_block_contents(func.body)
            self._dbg_enabled = False
            self._indent -= 1
        self._line("}")
        self._line("")

    # --- Output helpers ---
    def _line(self, text: str):
        """Emit physical lines with current indentation."""
        for part in text.split("\n"):
            if part.strip():
                if self._dbg_enabled:
                    self._emit_line_directive()
                self._lines.append("    " * self._indent + part)
            else:
                self._lines.append("")

    def _raw(self, text: str):
        """Emit raw text without indentation adjustment."""
        for line in text.rstrip("\n").split("\n"):
            self._lines.append(line)

    @staticmethod
    def _c_line_filename(path: str) -> str:
        """Encode a source path as one C string-literal payload."""

        escaped: list[str] = []
        for character in path:
            codepoint = ord(character)
            if character in {"\\", '"', "?"}:
                escaped.append("\\" + character)
            elif 0x20 <= codepoint < 0x7F:
                escaped.append(character)
            elif codepoint <= 0xFF:
                escaped.append(f"\\{codepoint:03o}")
            else:
                escaped.append(character)
        return "".join(escaped)

    def _emit_line_directive(self):
        """Map the next C line to its btrc origin or generated source."""

        if self._dbg_loc is not None:
            path = self._c_line_filename(self._dbg_loc[0])
            self._lines.append(f'#line {self._dbg_loc[1]} "{path}"')
            return
        cfile = self._module.debug_cfile or "<btrc-generated>"
        path = self._c_line_filename(cfile)
        self._lines.append(f'#line {self._CLINE_PLACEHOLDER} "{path}"')

    def _fix_cline_resets(self):
        """Resolve generated-source placeholders after final layout is known."""

        for index, line in enumerate(self._lines):
            if self._CLINE_PLACEHOLDER in line:
                self._lines[index] = line.replace(
                    self._CLINE_PLACEHOLDER,
                    str(index + 2),
                )

    def _compound(
        self,
        opening: str,
        values: list[str],
        closing: str,
        *,
        inline_separator: str = "",
        line_separator: str = "\n",
    ) -> str:
        """Keep one structured expression group within the inline budget."""

        inline = opening + inline_separator.join(values) + closing
        if "\n" not in inline and len(inline) <= _INLINE_EXPRESSION_LIMIT:
            return inline
        return opening + "\n" + line_separator.join(values) + "\n" + closing

    def _delimited(
        self,
        opening: str,
        values: list[str],
        closing: str,
    ) -> str:
        """Format a structured expression list without oversized C lines."""

        return self._compound(
            opening,
            values,
            closing,
            inline_separator=", ",
            line_separator=",\n",
        )

    def _cond_expr(self, expression: IRExpr) -> str:
        """Emit an expression for use as a control-flow condition."""

        result = self._expr(expression)
        if result.startswith("(") and result.endswith(")"):
            depth = 0
            quote = None
            escaped = False
            for index, character in enumerate(result):
                if quote is not None:
                    if escaped:
                        escaped = False
                    elif character == "\\":
                        escaped = True
                    elif character == quote:
                        quote = None
                    continue
                if character in ("'", '"'):
                    quote = character
                    continue
                if character == "(":
                    depth += 1
                elif character == ")":
                    depth -= 1
                if depth == 0 and index < len(result) - 1:
                    break
            else:
                result = result[1:-1]
        return result

    def _discarded_expr(self, expression: IRExpr) -> str:
        """Render an expression whose value is intentionally discarded."""

        return self._compound("(void)(", [self._expr(expression)], ")")

    def _expr(self, expression: IRExpr) -> str:
        if expression is None:
            raise TypeError("cannot emit a null IR expression")

        if isinstance(expression, IRLiteral):
            return expression.text
        if isinstance(expression, (IRVar, IRFunctionRef)):
            return expression.name
        if isinstance(expression, IRBinOp):
            return self._compound(
                "(",
                [
                    self._expr(expression.left),
                    expression.op,
                    self._expr(expression.right),
                ],
                ")",
                inline_separator=" ",
            )
        if isinstance(expression, IRCommaExpr):
            return self._delimited(
                "(",
                [self._expr(item) for item in expression.expressions],
                ")",
            )
        if isinstance(expression, IRUnaryOp):
            if expression.prefix:
                return self._compound(
                    f"({expression.op}",
                    [self._expr(expression.operand)],
                    ")",
                )
            return self._compound(
                "(",
                [self._expr(expression.operand)],
                f"{expression.op})",
            )
        if isinstance(expression, IRCall):
            arguments = self._delimited(
                "(",
                [self._expr(argument) for argument in expression.args],
                ")",
            )
            callee = (
                expression.callee
                if isinstance(expression.callee, str)
                else self._expr(expression.callee)
            )
            return self._compound("", [callee, arguments], "")
        if isinstance(expression, IRFieldAccess):
            operator = "->" if expression.arrow else "."
            return self._compound(
                "",
                [self._expr(expression.obj), f"{operator}{expression.field}"],
                "",
            )
        if isinstance(expression, IRCast):
            return self._compound(
                f"(({expression.target_type})",
                [self._expr(expression.expr)],
                ")",
            )
        if isinstance(expression, IRTernary):
            return self._compound(
                "(",
                [
                    self._expr(expression.condition),
                    "?",
                    self._expr(expression.true_expr),
                    ":",
                    self._expr(expression.false_expr),
                ],
                ")",
                inline_separator=" ",
            )
        if isinstance(expression, IRSizeof):
            operand = (
                self._expr(expression.operand)
                if isinstance(expression.operand, IRExpr)
                else str(expression.operand)
            )
            return self._compound("sizeof(", [operand], ")")
        if isinstance(expression, IRInitializerList):
            values = [self._expr(value) for value in expression.elements] or ["0"]
            return self._delimited("{", values, "}")
        if isinstance(expression, IRCompoundLiteral):
            fields = [
                self._compound(
                    f".{name} = ",
                    [self._expr(value)],
                    "",
                )
                for name, value in expression.fields
            ] or ["0"]
            return self._compound(
                f"({expression.c_type})",
                [self._delimited("{", fields, "}")],
                "",
            )
        if isinstance(expression, IRIndex):
            index = self._compound("[", [self._expr(expression.index)], "]")
            return self._compound("", [self._expr(expression.obj), index], "")
        if isinstance(expression, IRAddressOf):
            return self._compound("(&", [self._expr(expression.expr)], ")")
        if isinstance(expression, IRDeref):
            return self._compound("(*", [self._expr(expression.expr)], ")")
        if isinstance(expression, IRStmtExpr):
            for statement in expression.stmts:
                safe_initializer = isinstance(statement, IRVarDecl) and (
                    statement.init is None
                    or (
                        isinstance(statement.init, IRLiteral)
                        and statement.init.text in {"0", "NULL", "false"}
                    )
                )
                if not safe_initializer:
                    raise ValueError(
                        "IRStmtExpr setup permits uninitialized variable declarations "
                        "or declarations with a literal zero initializer only"
                    )
                self._emit_stmt(statement)
            return self._expr(expression.result)
        raise TypeError(f"unsupported IR expression: {type(expression).__name__}")

    @staticmethod
    def _qualified_decl_type(declaration: IRVarDecl) -> str:
        """Format a local declaration's storage and volatile qualifiers."""

        if declaration.is_static and declaration.is_extern:
            raise ValueError(
                f"IR variable {declaration.name!r} is both static and extern"
            )
        storage = (
            "static "
            if declaration.is_static
            else "extern "
            if declaration.is_extern
            else ""
        )
        return storage + CType.qualify_volatile_object(
            str(declaration.c_type),
            declaration.is_volatile,
        )

    @staticmethod
    def _qualified_global_type(declaration: IRGlobalDecl) -> str:
        if declaration.is_static and declaration.is_extern:
            raise ValueError(
                f"IR global {declaration.name!r} is both static and extern"
            )
        storage = (
            "static "
            if declaration.is_static
            else "extern "
            if declaration.is_extern
            else ""
        )
        return storage + CType.qualify_volatile_object(
            str(declaration.c_type),
            declaration.is_volatile,
        )

    def _emit_global_decl(self, declaration: IRGlobalDecl):
        suffix = (
            f"[{self._expr(declaration.array_size)}]"
            if declaration.array_size is not None
            else "[]"
            if declaration.is_unsized_array
            else ""
        )
        initializer = (
            f" = {self._expr(declaration.init)}" if declaration.init else ""
        )
        self._line(
            f"{self._qualified_global_type(declaration)} "
            f"{declaration.name}{suffix}{initializer};"
        )

    def _emit_block_contents(self, block):
        for statement in block.stmts:
            self._emit_stmt(statement)

    def _emit_stmt(self, statement: IRStmt):
        if isinstance(statement, IRLineMarker):
            self._dbg_loc = (statement.file, statement.line)
            return
        if isinstance(statement, IRVarDecl):
            c_type = self._qualified_decl_type(statement)
            array = (
                f"[{self._expr(statement.array_size)}]"
                if statement.array_size is not None
                else "[]"
                if statement.is_unsized_array
                else ""
            )
            initializer = (
                f" = {self._expr(statement.init)}" if statement.init else ""
            )
            self._line(
                f"{c_type} {statement.name}{array}{initializer};"
            )
        elif isinstance(statement, IRAssign):
            self._line(
                f"{self._expr(statement.target)} = "
                f"{self._expr(statement.value)};"
            )
        elif isinstance(statement, IRReturn):
            value = f" {self._expr(statement.value)}" if statement.value else ""
            self._line(f"return{value};")
        elif isinstance(statement, IRBlock):
            self._line("{")
            self._indent += 1
            self._emit_block_contents(statement)
            self._indent -= 1
            self._line("}")
        elif isinstance(statement, IRIf):
            self._line(f"if ({self._cond_expr(statement.condition)}) {{")
            if statement.then_block:
                self._indent += 1
                self._emit_block_contents(statement.then_block)
                self._indent -= 1
            self._emit_else_tail(statement)
        elif isinstance(statement, IRWhile):
            self._line(f"while ({self._cond_expr(statement.condition)}) {{")
            if statement.body:
                self._indent += 1
                self._emit_block_contents(statement.body)
                self._indent -= 1
            self._line("}")
        elif isinstance(statement, IRDoWhile):
            condition = self._cond_expr(statement.condition)
            self._line("do {")
            if statement.body:
                self._indent += 1
                self._emit_block_contents(statement.body)
                self._indent -= 1
            self._line(f"}} while ({condition});")
        elif isinstance(statement, IRFor):
            initialization = self._for_init_text(statement.init)
            condition = self._expr(statement.condition) if statement.condition else ""
            update = self._expr(statement.update) if statement.update else ""
            self._line(f"for ({initialization}; {condition}; {update}) {{")
            if statement.body:
                self._indent += 1
                self._emit_block_contents(statement.body)
                self._indent -= 1
            self._line("}")
        elif isinstance(statement, IRSwitch):
            self._line(f"switch ({self._expr(statement.value)}) {{")
            self._indent += 1
            for index, case in enumerate(statement.cases):
                label = (
                    f"case {self._expr(case.value)}:"
                    if case.value
                    else "default:"
                )
                self._line(label)
                self._line("{")
                self._indent += 1
                for child in case.body:
                    self._emit_stmt(child)
                self._indent -= 1
                self._line("}")
                if case.falls_through and index + 1 < len(statement.cases):
                    self._line("/* fall through */")
            self._indent -= 1
            self._line("}")
        elif isinstance(statement, IRExprStmt):
            self._line(f"{self._discarded_expr(statement.expr)};")
        elif isinstance(statement, IRBreak):
            self._line("break;")
        elif isinstance(statement, IRContinue):
            self._line("continue;")
        elif isinstance(statement, IRGpuKernel):
            self._emit_gpu_kernel(statement)
        else:
            raise TypeError(
                f"unsupported IR statement: {type(statement).__name__}"
            )

    def _for_init_text(self, initialization) -> str:
        if isinstance(initialization, IRVarDecl):
            c_type = self._qualified_decl_type(initialization)
            array = (
                f"[{self._expr(initialization.array_size)}]"
                if initialization.array_size is not None
                else "[]"
                if initialization.is_unsized_array
                else ""
            )
            initializer = (
                f" = {self._expr(initialization.init)}"
                if initialization.init
                else ""
            )
            return f"{c_type} {initialization.name}{array}{initializer}"
        if isinstance(initialization, IRAssign):
            return (
                f"{self._expr(initialization.target)} = "
                f"{self._expr(initialization.value)}"
            )
        if isinstance(initialization, IRExprStmt):
            return self._discarded_expr(initialization.expr)
        if initialization is None:
            return ""
        raise TypeError(
            "unsupported IR for-loop initializer: "
            f"{type(initialization).__name__}"
        )

    def _emit_else_tail(self, statement: IRIf):
        if not statement.else_block or not statement.else_block.stmts:
            self._line("}")
            return
        self._line("} else {")
        self._indent += 1
        self._emit_block_contents(statement.else_block)
        self._indent -= 1
        self._line("}")

    def _emit_type_declaration(self, declaration):
        """Format one already-ordered typed declaration."""

        if isinstance(declaration, IREnumDef):
            self._emit_enum_def(declaration)
        elif isinstance(declaration, IRFunctionPointerTypedef):
            self._emit_function_pointer_typedef(declaration)
            self._line("")
        elif isinstance(declaration, IRTypedefDef):
            self._emit_typedef(declaration)
        elif isinstance(declaration, IRTaggedUnionDef):
            self._emit_tagged_union(declaration)
        elif isinstance(declaration, IRStructDef):
            self._emit_struct(declaration)
        else:
            raise TypeError(
                f"unsupported typed declaration {type(declaration).__name__}"
            )

    def _emit_enum_def(self, enum: IREnumDef):
        self._line("typedef enum {" if enum.name is not None else "enum {")
        self._indent += 1
        for index, value in enumerate(enum.values):
            comma = "," if index < len(enum.values) - 1 else ""
            suffix = (
                f" = {self._expr(value.value)}"
                if value.value is not None
                else ""
            )
            self._line(f"{value.name}{suffix}{comma}")
        self._indent -= 1
        self._line(f"}} {enum.name};" if enum.name is not None else "};")
        self._line("")

    def _emit_struct_forward(self, declaration: IRStructForward):
        self._line(
            f"typedef struct {declaration.name} {declaration.name};"
        )

    def _emit_function_pointer_typedef(
        self,
        declaration: IRFunctionPointerTypedef,
    ):
        parameters = ", ".join(map(str, declaration.param_types)) or "void"
        self._line(
            f"typedef {declaration.return_type} "
            f"(*{declaration.name})({parameters});"
        )

    @staticmethod
    def _function_signature(declaration: IRFunctionDecl) -> str:
        parameters = (
            ", ".join(
                f"{CType.qualify_volatile_object(str(parameter.c_type), parameter.is_volatile)} "
                f"{parameter.name}"
                for parameter in declaration.params
            )
            or "void"
        )
        storage = "static " if declaration.is_static else ""
        return (
            f"{storage}{declaration.return_type} "
            f"{declaration.name}({parameters})"
        )

    def _emit_function_decl(self, declaration: IRFunctionDecl):
        self._line(f"{self._function_signature(declaration)};")

    def _emit_typedef(self, typedef: IRTypedefDef):
        target_type = CType.qualify_volatile_object(
            str(typedef.target_type),
            typedef.is_volatile,
        )
        self._line(f"typedef {target_type} {typedef.name};")
        self._line("")

    def _emit_tagged_union(self, tagged: IRTaggedUnionDef):
        payload_variants = [
            variant for variant in tagged.variants if variant.fields
        ]
        for variant in payload_variants:
            data_name = f"{tagged.name}_{variant.name}_Data"
            self._line(f"typedef struct {data_name} {{")
            self._indent += 1
            for field in variant.fields:
                c_type = CType.qualify_volatile_object(
                    str(field.c_type),
                    field.is_volatile,
                )
                self._line(f"{c_type} {field.name};")
            self._indent -= 1
            self._line(f"}} {data_name};")
            self._line("")

        self._line(f"struct {tagged.name} {{")
        self._indent += 1
        self._line(f"{tagged.tag_type} tag;")
        if payload_variants:
            self._line("union {")
            self._indent += 1
            for variant in payload_variants:
                data_name = f"{tagged.name}_{variant.name}_Data"
                self._line(f"{data_name} {variant.name};")
            self._indent -= 1
            self._line("} data;")
        self._indent -= 1
        self._line("};")
        self._line("")

    def _emit_struct(self, struct: IRStructDef):
        if struct.pack_alignment is not None:
            self._line(f"#pragma pack(push, {struct.pack_alignment})")
        self._line(f"struct {struct.name} {{")
        self._indent += 1
        for field in struct.fields:
            suffix = (
                f"[{self._expr(field.array_size)}]"
                if field.array_size is not None
                else ""
            )
            c_type = CType.qualify_volatile_object(
                str(field.c_type),
                field.is_volatile,
            )
            self._line(f"{c_type} {field.name}{suffix};")
        self._indent -= 1
        self._line("};")
        if struct.pack_alignment is not None:
            self._line("#pragma pack(pop)")
        self._line("")

    @staticmethod
    def _include_text(include: IRInclude) -> str:
        if include.is_system:
            return f"#include <{include.header}>"
        return f'#include "{include.header}"'

    @staticmethod
    def _macro_text(macro: IRMacroDef) -> str:
        parameters = "" if macro.params is None else f"({', '.join(macro.params)})"
        replacement = f" {macro.replacement}" if macro.replacement else ""
        return f"#define {macro.name}{parameters}{replacement}"

    def _preprocessor_text(
        self,
        declaration: IRInclude | IRMacroDef,
    ) -> str:
        if isinstance(declaration, IRInclude):
            return self._include_text(declaration)
        return self._macro_text(declaration)

    def _emit_preprocessor_declarations(self, module: IRModule) -> None:
        for declaration in module.preprocessor_decls:
            self._line(self._preprocessor_text(declaration))
        if module.preprocessor_decls:
            self._line("")

    def _emit_gpu_kernel(self, kernel: IRGpuKernel):
        source = WgslEmitter.emit_ir_kernel(kernel)
        escaped = (
            source.replace("\\", "\\\\")
            .replace('"', '\\"')
            .replace("\n", "\\n")
        )
        self._line(
            f'static const char* {kernel.name}_wgsl = "{escaped}";'
        )
        self._line("")
