manifest-version = 1

[package]
name = "btrc_stdlib_terminal"
exports = ["Terminal", "TerminalCStringArray", "TerminalClock", "TerminalPassword", "TerminalPasswordExchange", "TerminalPasswordPrompts"]
