"""Generate the self-hosted compiler's hosted-ABI policy tables."""

from __future__ import annotations

import argparse
import math
from pathlib import Path

from .hosted_abi import (
    HOSTED_FUNCTION_OWNED_NAMES,
    HOSTED_FUNCTIONS,
    HOSTED_MACROS,
    HOSTED_OWNED_NAMES,
    HOSTED_TYPE_NAMES,
    HOSTED_TYPEDEF_NAMES,
)
from .hosted_abi_btrc_dispatch import dispatcher_source
from .hosted_abi_generation_io import (
    check_generated_files,
    publish_generated_files,
)
from .hosted_abi_runtime import (
    SOURCE_RUNTIME_ADOPTING_HELPERS,
    SOURCE_RUNTIME_HELPERS,
)

_ROOT = Path(__file__).resolve().parents[2]
_BTRC = _ROOT / "compiler" / "btrc"
_GENERATED = _BTRC / "generated" / "hosted_abi"
_CHUNK_CAPACITY = 180
_GENERATED_MODE = 0o644
_LEGACY_GLOBS = ("hosted_abi_exact_generated.btrc", "hosted_abi_owned_generated_*.btrc")


def _encode_type(type_shape) -> str:
    return ",".join(
        (
            type_shape.base,
            str(type_shape.pointer_depth),
            "1" if type_shape.is_const else "0",
        )
    )


def _encode_spec(spec) -> str:
    semantic = spec.semantic_result or spec.result
    header = ",".join(
        (
            _encode_type(spec.result),
            _encode_type(semantic),
            "1" if spec.variadic else "0",
            spec.return_effect,
            str(spec.return_alias_parameter if spec.return_alias_parameter is not None else -1),
            "1" if spec.raw_lifetime else "0",
            spec.return_alias_null_effect or "none",
            spec.return_deallocator or "none",
            spec.return_alias_shape or "none",
            spec.consume_deallocator or "none",
            spec.return_alias_null_deallocator or "none",
        )
    )
    parameters = spec.parameters or ()
    encoded_parameters = (
        f"{_encode_type(parameter)},{spec.effects[index]}" for index, parameter in enumerate(parameters)
    )
    return ";".join((header, *encoded_parameters))


def _exact_source(index: int, entries) -> str:
    lines = [
        "/* GENERATED by compiler/python/gen_hosted_abi_btrc.py. */",
        f"string hostedAbiEncodedSpecGenerated{index}(string name) {{",
    ]
    for name, spec in entries:
        lines.append(f'    if (name == "{name}") {{ return "{_encode_spec(spec)}"; }}')
    lines.extend(('    return "";', "}", ""))
    return "\n".join(lines)


def _name_set_source(function_name: str, names: list[str]) -> str:
    lines = [
        "/* GENERATED by compiler/python/gen_hosted_abi_btrc.py. */",
        f"bool {function_name}(string name) {{",
    ]
    if names:
        lines.append(f'    return name == "{names[0]}"')
        lines.extend(f'        || name == "{name}"' for name in names[1:])
        lines[-1] += ";"
    else:
        lines.append("    return false;")
    lines.extend(("}", ""))
    return "\n".join(lines)


def _chunk_count(size: int) -> int:
    return max(1, math.ceil(size / _CHUNK_CAPACITY))


def _chunk_paths(prefix: str, count: int) -> tuple[Path, ...]:
    return tuple(_GENERATED / f"{prefix}_{index:02}.btrc" for index in range(count))


def render_files() -> dict[Path, str]:
    extras = sorted(HOSTED_OWNED_NAMES - HOSTED_FUNCTIONS.keys())
    function_extras = sorted(HOSTED_FUNCTION_OWNED_NAMES - HOSTED_FUNCTIONS.keys())
    exact = sorted(HOSTED_FUNCTIONS.items())
    exact_paths = _chunk_paths("exact", _chunk_count(len(exact)))
    function_paths = _chunk_paths("function", _chunk_count(len(function_extras)))
    macro_names = sorted(HOSTED_MACROS)
    macro_paths = _chunk_paths("macro", _chunk_count(len(macro_names)))
    type_names = sorted(HOSTED_TYPE_NAMES)
    type_paths = _chunk_paths("type", _chunk_count(len(type_names)))
    typedef_names = sorted(HOSTED_TYPEDEF_NAMES)
    typedef_paths = _chunk_paths("typedef", _chunk_count(len(typedef_names)))
    owned_paths = _chunk_paths("owned", _chunk_count(len(extras)))
    adopting_names = sorted(SOURCE_RUNTIME_ADOPTING_HELPERS)
    adopting_paths = _chunk_paths(
        "adopting",
        _chunk_count(len(adopting_names)),
    )
    source_helper_names = sorted(SOURCE_RUNTIME_HELPERS)
    source_helper_paths = _chunk_paths(
        "source_helper",
        _chunk_count(len(source_helper_names)),
    )
    files = {
        _GENERATED / "tables.btrc": dispatcher_source(
            exact_count=len(exact_paths),
            function_count=len(function_paths),
            macro_count=len(macro_paths),
            type_count=len(type_paths),
            typedef_count=len(typedef_paths),
            owned_count=len(owned_paths),
            adopting_count=len(adopting_paths),
            source_helper_count=len(source_helper_paths),
        )
    }
    for index, path in enumerate(exact_paths):
        start = index * _CHUNK_CAPACITY
        files[path] = _exact_source(
            index,
            exact[start : start + _CHUNK_CAPACITY],
        )
    for index, path in enumerate(owned_paths):
        start = index * _CHUNK_CAPACITY
        names = extras[start : start + _CHUNK_CAPACITY]
        files[path] = _name_set_source(f"hostedAbiOwnedGenerated{index}", names)
    for index, path in enumerate(adopting_paths):
        start = index * _CHUNK_CAPACITY
        names = adopting_names[start : start + _CHUNK_CAPACITY]
        files[path] = _name_set_source(
            f"hostedAbiSourceAdoptingHelperGenerated{index}",
            names,
        )
    for index, path in enumerate(source_helper_paths):
        start = index * _CHUNK_CAPACITY
        names = source_helper_names[start : start + _CHUNK_CAPACITY]
        files[path] = _name_set_source(
            f"hostedAbiSourceRuntimeHelperGenerated{index}",
            names,
        )
    for index, path in enumerate(function_paths):
        start = index * _CHUNK_CAPACITY
        names = function_extras[start : start + _CHUNK_CAPACITY]
        files[path] = _name_set_source(
            f"hostedAbiFunctionOwnedGenerated{index}",
            names,
        )
    for index, path in enumerate(macro_paths):
        start = index * _CHUNK_CAPACITY
        names = macro_names[start : start + _CHUNK_CAPACITY]
        files[path] = _name_set_source(
            f"hostedAbiMacroGenerated{index}",
            names,
        )
    for index, path in enumerate(type_paths):
        start = index * _CHUNK_CAPACITY
        names = type_names[start : start + _CHUNK_CAPACITY]
        files[path] = _name_set_source(
            f"hostedAbiTypeGenerated{index}",
            names,
        )
    for index, path in enumerate(typedef_paths):
        start = index * _CHUNK_CAPACITY
        names = typedef_names[start : start + _CHUNK_CAPACITY]
        files[path] = _name_set_source(
            f"hostedAbiTypedefGenerated{index}",
            names,
        )
    return files


def check_generated() -> int:
    files = render_files()
    return check_generated_files(
        files,
        generated=_GENERATED,
        legacy_root=_BTRC,
        legacy_globs=_LEGACY_GLOBS,
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.check:
        return check_generated()
    files = render_files()
    publish_generated_files(
        files,
        generated=_GENERATED,
        dispatcher=_GENERATED / "tables.btrc",
        legacy_root=_BTRC,
        legacy_globs=_LEGACY_GLOBS,
        mode=_GENERATED_MODE,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
