"""Render the generated self-host hosted-ABI dispatcher."""

from __future__ import annotations


def _boolean_dispatcher(name: str, chunk_prefix: str, count: int) -> list[str]:
    lines = [f"bool {name}(string name) {{"]
    lines.append(f"    return {chunk_prefix}0(name)")
    lines.extend(f"        || {chunk_prefix}{index}(name)" for index in range(1, count))
    lines[-1] += ";"
    lines.extend(("}", ""))
    return lines


def dispatcher_source(
    *,
    exact_count: int,
    function_count: int,
    macro_count: int,
    type_count: int,
    typedef_count: int,
    owned_count: int,
    adopting_count: int,
    source_helper_count: int,
) -> str:
    includes = [
        *(f'#include "exact_{index:02}.btrc"' for index in range(exact_count)),
        *(f'#include "function_{index:02}.btrc"' for index in range(function_count)),
        *(f'#include "macro_{index:02}.btrc"' for index in range(macro_count)),
        *(f'#include "type_{index:02}.btrc"' for index in range(type_count)),
        *(f'#include "typedef_{index:02}.btrc"' for index in range(typedef_count)),
        *(f'#include "owned_{index:02}.btrc"' for index in range(owned_count)),
        *(f'#include "adopting_{index:02}.btrc"' for index in range(adopting_count)),
        *(f'#include "source_helper_{index:02}.btrc"' for index in range(source_helper_count)),
    ]
    lines = [
        "/* GENERATED by compiler/python/gen_hosted_abi_btrc.py. */",
        *includes,
        "",
        "string hostedAbiEncodedSpecGenerated(string name) {",
    ]
    for index in range(exact_count):
        lines.extend(
            (
                f"    string encoded{index} = hostedAbiEncodedSpecGenerated{index}(name);",
                f'    if (encoded{index} != "") {{ return encoded{index}; }}',
            )
        )
    lines.extend(('    return "";', "}", ""))
    dispatchers = (
        (
            "hostedAbiSourceAdoptingHelperGenerated",
            "hostedAbiSourceAdoptingHelperGenerated",
            adopting_count,
        ),
        (
            "hostedAbiSourceRuntimeHelperGenerated",
            "hostedAbiSourceRuntimeHelperGenerated",
            source_helper_count,
        ),
        ("hostedAbiTypedefGenerated", "hostedAbiTypedefGenerated", typedef_count),
        ("hostedAbiTypeGenerated", "hostedAbiTypeGenerated", type_count),
        ("hostedAbiMacroGenerated", "hostedAbiMacroGenerated", macro_count),
        (
            "hostedAbiFunctionOwnedGenerated",
            "hostedAbiFunctionOwnedGenerated",
            function_count,
        ),
        ("hostedAbiOwnedGenerated", "hostedAbiOwnedGenerated", owned_count),
    )
    for name, prefix, count in dispatchers:
        lines.extend(_boolean_dispatcher(name, prefix, count))
    return "\n".join(lines)


__all__ = ["dispatcher_source"]
