"""Owned names and exact representable ABI specs from ``stdlib.h``."""

from .hosted_abi_model import (
    ALIAS_EXACT,
    CHAR_PTR,
    CHAR_PTR_PTR,
    CONST_CHAR_PTR,
    CONSUME,
    DEALLOC_FREE,
    DOUBLE,
    FLOAT,
    INT,
    LDOUBLE,
    LLONG,
    LONG,
    MUTATE,
    READ,
    RETURN_ALIAS,
    RETURN_FRESH,
    RETURN_INDEPENDENT,
    SIZE,
    UINT,
    ULLONG,
    ULONG,
    VALUE,
    VOID,
    VOID_PTR,
    HostedFunction,
    function,
)

HOSTED_STDLIB_NAMES = frozenset(
    [
        "atof",
        "atoi",
        "atol",
        "atoll",
        "strtod",
        "strtof",
        "strtold",
        "strtol",
        "strtoll",
        "strtoul",
        "strtoull",
        "rand",
        "srand",
        "aligned_alloc",
        "calloc",
        "free",
        "malloc",
        "realloc",
        "reallocarray",
        "abort",
        "atexit",
        "at_quick_exit",
        "exit",
        "_Exit",
        "quick_exit",
        "getenv",
        "system",
        "bsearch",
        "qsort",
        "abs",
        "labs",
        "llabs",
        "div",
        "ldiv",
        "lldiv",
        "mblen",
        "mbtowc",
        "wctomb",
        "mbstowcs",
        "wcstombs",
        "mkdtemp",
    ]
)

HOSTED_STDLIB_FUNCTIONS: dict[str, HostedFunction] = {
    "atof": function(DOUBLE, CONST_CHAR_PTR, effects=(READ,)),
    "atoi": function(INT, CONST_CHAR_PTR, effects=(READ,)),
    "atol": function(LONG, CONST_CHAR_PTR, effects=(READ,)),
    "atoll": function(LLONG, CONST_CHAR_PTR, effects=(READ,)),
    "strtod": function(DOUBLE, CONST_CHAR_PTR, CHAR_PTR_PTR, effects=(READ, MUTATE)),
    "strtof": function(FLOAT, CONST_CHAR_PTR, CHAR_PTR_PTR, effects=(READ, MUTATE)),
    "strtold": function(LDOUBLE, CONST_CHAR_PTR, CHAR_PTR_PTR, effects=(READ, MUTATE)),
    "strtol": function(LONG, CONST_CHAR_PTR, CHAR_PTR_PTR, INT, effects=(READ, MUTATE, VALUE)),
    "strtoul": function(ULONG, CONST_CHAR_PTR, CHAR_PTR_PTR, INT, effects=(READ, MUTATE, VALUE)),
    "strtoll": function(LLONG, CONST_CHAR_PTR, CHAR_PTR_PTR, INT, effects=(READ, MUTATE, VALUE)),
    "strtoull": function(ULLONG, CONST_CHAR_PTR, CHAR_PTR_PTR, INT, effects=(READ, MUTATE, VALUE)),
    "rand": function(INT),
    "srand": function(VOID, UINT),
    "aligned_alloc": function(
        VOID_PTR,
        SIZE,
        SIZE,
        return_effect=RETURN_FRESH,
        return_deallocator=DEALLOC_FREE,
    ),
    "calloc": function(
        VOID_PTR,
        SIZE,
        SIZE,
        return_effect=RETURN_FRESH,
        return_deallocator=DEALLOC_FREE,
    ),
    "malloc": function(
        VOID_PTR,
        SIZE,
        return_effect=RETURN_FRESH,
        return_deallocator=DEALLOC_FREE,
    ),
    "realloc": function(
        VOID_PTR,
        VOID_PTR,
        SIZE,
        effects=(CONSUME, VALUE),
        return_effect=RETURN_FRESH,
        raw_lifetime=True,
        return_deallocator=DEALLOC_FREE,
        consume_deallocator=DEALLOC_FREE,
    ),
    "reallocarray": function(
        VOID_PTR,
        VOID_PTR,
        SIZE,
        SIZE,
        effects=(CONSUME, VALUE, VALUE),
        return_effect=RETURN_FRESH,
        raw_lifetime=True,
        return_deallocator=DEALLOC_FREE,
        consume_deallocator=DEALLOC_FREE,
    ),
    "free": function(
        VOID,
        VOID_PTR,
        effects=(CONSUME,),
        raw_lifetime=True,
        consume_deallocator=DEALLOC_FREE,
    ),
    "abort": function(VOID),
    "exit": function(VOID, INT),
    "_Exit": function(VOID, INT),
    "quick_exit": function(VOID, INT),
    "getenv": function(
        CHAR_PTR,
        CONST_CHAR_PTR,
        effects=(READ,),
        return_effect=RETURN_INDEPENDENT,
    ),
    "system": function(INT, CONST_CHAR_PTR, effects=(READ,)),
    "abs": function(INT, INT),
    "labs": function(LONG, LONG),
    "llabs": function(LLONG, LLONG),
    "mblen": function(INT, CONST_CHAR_PTR, SIZE, effects=(READ, VALUE)),
    "mkdtemp": function(
        CHAR_PTR,
        CHAR_PTR,
        effects=(MUTATE,),
        return_effect=RETURN_ALIAS,
        return_alias_parameter=0,
        return_alias_shape=ALIAS_EXACT,
    ),
}

__all__ = ["HOSTED_STDLIB_FUNCTIONS", "HOSTED_STDLIB_NAMES"]
