"""Compiler-used ``setjmp.h`` and POSIX ``pthread.h`` ABI ownership."""

from .hosted_abi_model import (
    INT,
    MUTATE,
    READ,
    VALUE,
    HostedFunction,
    abi_type,
    function,
)

HOSTED_SETJMP_NAMES = frozenset({"setjmp", "longjmp", "_setjmp", "sigsetjmp", "siglongjmp"})
HOSTED_PTHREAD_NAMES = frozenset(
    {
        # POSIX.1 pthread function namespace.  Only the compiler-used subset
        # below has a source-representable exact ABI; every spelling is still
        # owned because generated translations may include <pthread.h>.
        "pthread_atfork",
        "pthread_attr_destroy",
        "pthread_attr_getdetachstate",
        "pthread_attr_getguardsize",
        "pthread_attr_getinheritsched",
        "pthread_attr_getschedparam",
        "pthread_attr_getschedpolicy",
        "pthread_attr_getscope",
        "pthread_attr_getstack",
        "pthread_attr_getstackaddr",
        "pthread_attr_getstacksize",
        "pthread_attr_init",
        "pthread_attr_setdetachstate",
        "pthread_attr_setguardsize",
        "pthread_attr_setinheritsched",
        "pthread_attr_setschedparam",
        "pthread_attr_setschedpolicy",
        "pthread_attr_setscope",
        "pthread_attr_setstack",
        "pthread_attr_setstackaddr",
        "pthread_attr_setstacksize",
        "pthread_barrier_destroy",
        "pthread_barrier_init",
        "pthread_barrier_wait",
        "pthread_barrierattr_destroy",
        "pthread_barrierattr_getpshared",
        "pthread_barrierattr_init",
        "pthread_barrierattr_setpshared",
        "pthread_cancel",
        "pthread_cleanup_pop",
        "pthread_cleanup_push",
        "pthread_cond_broadcast",
        "pthread_cond_destroy",
        "pthread_cond_init",
        "pthread_cond_signal",
        "pthread_cond_timedwait",
        "pthread_cond_wait",
        "pthread_condattr_destroy",
        "pthread_condattr_getclock",
        "pthread_condattr_getpshared",
        "pthread_condattr_init",
        "pthread_condattr_setclock",
        "pthread_condattr_setpshared",
        "pthread_create",
        "pthread_detach",
        "pthread_equal",
        "pthread_exit",
        "pthread_getconcurrency",
        "pthread_getcpuclockid",
        "pthread_getschedparam",
        "pthread_getspecific",
        "pthread_join",
        "pthread_key_create",
        "pthread_key_delete",
        "pthread_kill",
        "pthread_mutex_consistent",
        "pthread_mutex_destroy",
        "pthread_mutex_getprioceiling",
        "pthread_mutex_init",
        "pthread_mutex_lock",
        "pthread_mutex_setprioceiling",
        "pthread_mutex_timedlock",
        "pthread_mutex_trylock",
        "pthread_mutex_unlock",
        "pthread_mutexattr_destroy",
        "pthread_mutexattr_getprioceiling",
        "pthread_mutexattr_getprotocol",
        "pthread_mutexattr_getpshared",
        "pthread_mutexattr_getrobust",
        "pthread_mutexattr_gettype",
        "pthread_mutexattr_init",
        "pthread_mutexattr_setprioceiling",
        "pthread_mutexattr_setprotocol",
        "pthread_mutexattr_setpshared",
        "pthread_mutexattr_setrobust",
        "pthread_mutexattr_settype",
        "pthread_once",
        "pthread_rwlock_destroy",
        "pthread_rwlock_init",
        "pthread_rwlock_rdlock",
        "pthread_rwlock_timedrdlock",
        "pthread_rwlock_timedwrlock",
        "pthread_rwlock_tryrdlock",
        "pthread_rwlock_trywrlock",
        "pthread_rwlock_unlock",
        "pthread_rwlock_wrlock",
        "pthread_rwlockattr_destroy",
        "pthread_rwlockattr_getpshared",
        "pthread_rwlockattr_init",
        "pthread_rwlockattr_setpshared",
        "pthread_self",
        "pthread_setcancelstate",
        "pthread_setcanceltype",
        "pthread_setconcurrency",
        "pthread_setschedparam",
        "pthread_setschedprio",
        "pthread_setspecific",
        "pthread_sigmask",
        "pthread_spin_destroy",
        "pthread_spin_init",
        "pthread_spin_lock",
        "pthread_spin_trylock",
        "pthread_spin_unlock",
        "pthread_testcancel",
    }
)

_PTHREAD = abi_type("pthread_t")
_PTHREAD_MUTEX_PTR = abi_type("pthread_mutex_t", 1)
_CONST_PTHREAD_MUTEX_ATTR_PTR = abi_type("pthread_mutexattr_t", 1, const=True)
_VOID_PTR_PTR = abi_type("void", 2)

HOSTED_CONCURRENCY_FUNCTIONS: dict[str, HostedFunction] = {
    "pthread_join": function(
        INT,
        _PTHREAD,
        _VOID_PTR_PTR,
        effects=(VALUE, MUTATE),
    ),
    "pthread_mutex_init": function(
        INT,
        _PTHREAD_MUTEX_PTR,
        _CONST_PTHREAD_MUTEX_ATTR_PTR,
        effects=(MUTATE, READ),
    ),
    "pthread_mutex_destroy": function(INT, _PTHREAD_MUTEX_PTR, effects=(MUTATE,)),
    "pthread_mutex_lock": function(INT, _PTHREAD_MUTEX_PTR, effects=(MUTATE,)),
    "pthread_mutex_unlock": function(INT, _PTHREAD_MUTEX_PTR, effects=(MUTATE,)),
}

HOSTED_CONCURRENCY_NAMES = HOSTED_SETJMP_NAMES | HOSTED_PTHREAD_NAMES

__all__ = [
    "HOSTED_CONCURRENCY_FUNCTIONS",
    "HOSTED_CONCURRENCY_NAMES",
    "HOSTED_PTHREAD_NAMES",
    "HOSTED_SETJMP_NAMES",
]
