"""Owned names and exact ABI specs from ``string.h``."""

from .hosted_abi_model import (
    ALIAS_EXACT,
    ALIAS_INTERIOR,
    CHAR_PTR,
    CONST_CHAR_PTR,
    CONST_VOID_PTR,
    DEALLOC_FREE,
    INT,
    MUTATE,
    READ,
    RETURN_ALIAS,
    RETURN_FRESH,
    RETURN_INDEPENDENT,
    RETURN_OPAQUE,
    SIZE,
    VALUE,
    VOID_PTR,
    HostedFunction,
    function,
)

HOSTED_STRING_NAMES = frozenset(
    [
        "memcpy",
        "memmove",
        "strcpy",
        "strncpy",
        "strcat",
        "strncat",
        "memcmp",
        "strcmp",
        "strcoll",
        "strncmp",
        "strxfrm",
        "memchr",
        "strchr",
        "strcspn",
        "strpbrk",
        "strrchr",
        "strspn",
        "strstr",
        "strtok",
        "memset",
        "strerror",
        "strlen",
        "strdup",
        "strnlen",
    ]
)


def _destination(result, *parameters, effects) -> HostedFunction:
    return function(
        result,
        *parameters,
        effects=effects,
        return_effect=RETURN_ALIAS,
        return_alias_parameter=0,
        return_alias_shape=ALIAS_EXACT,
    )


HOSTED_STRING_FUNCTIONS: dict[str, HostedFunction] = {
    "memcpy": _destination(VOID_PTR, VOID_PTR, CONST_VOID_PTR, SIZE, effects=(MUTATE, READ, VALUE)),
    "memmove": _destination(VOID_PTR, VOID_PTR, CONST_VOID_PTR, SIZE, effects=(MUTATE, READ, VALUE)),
    "strcpy": _destination(CHAR_PTR, CHAR_PTR, CONST_CHAR_PTR, effects=(MUTATE, READ)),
    "strncpy": _destination(CHAR_PTR, CHAR_PTR, CONST_CHAR_PTR, SIZE, effects=(MUTATE, READ, VALUE)),
    "strcat": _destination(CHAR_PTR, CHAR_PTR, CONST_CHAR_PTR, effects=(MUTATE, READ)),
    "strncat": _destination(CHAR_PTR, CHAR_PTR, CONST_CHAR_PTR, SIZE, effects=(MUTATE, READ, VALUE)),
    "memcmp": function(INT, CONST_VOID_PTR, CONST_VOID_PTR, SIZE, effects=(READ, READ, VALUE)),
    "strcmp": function(INT, CONST_CHAR_PTR, CONST_CHAR_PTR, effects=(READ, READ)),
    "strcoll": function(INT, CONST_CHAR_PTR, CONST_CHAR_PTR, effects=(READ, READ)),
    "strncmp": function(INT, CONST_CHAR_PTR, CONST_CHAR_PTR, SIZE, effects=(READ, READ, VALUE)),
    "strxfrm": function(SIZE, CHAR_PTR, CONST_CHAR_PTR, SIZE, effects=(MUTATE, READ, VALUE)),
    "memchr": function(
        VOID_PTR,
        CONST_VOID_PTR,
        INT,
        SIZE,
        effects=(READ, VALUE, VALUE),
        return_effect=RETURN_ALIAS,
        return_alias_parameter=0,
        return_alias_shape=ALIAS_INTERIOR,
    ),
    "strchr": function(
        CHAR_PTR,
        CONST_CHAR_PTR,
        INT,
        effects=(READ, VALUE),
        return_effect=RETURN_ALIAS,
        return_alias_parameter=0,
        return_alias_shape=ALIAS_INTERIOR,
    ),
    "strcspn": function(SIZE, CONST_CHAR_PTR, CONST_CHAR_PTR, effects=(READ, READ)),
    "strpbrk": function(
        CHAR_PTR,
        CONST_CHAR_PTR,
        CONST_CHAR_PTR,
        effects=(READ, READ),
        return_effect=RETURN_ALIAS,
        return_alias_parameter=0,
        return_alias_shape=ALIAS_INTERIOR,
    ),
    "strrchr": function(
        CHAR_PTR,
        CONST_CHAR_PTR,
        INT,
        effects=(READ, VALUE),
        return_effect=RETURN_ALIAS,
        return_alias_parameter=0,
        return_alias_shape=ALIAS_INTERIOR,
    ),
    "strspn": function(SIZE, CONST_CHAR_PTR, CONST_CHAR_PTR, effects=(READ, READ)),
    "strstr": function(
        CHAR_PTR,
        CONST_CHAR_PTR,
        CONST_CHAR_PTR,
        effects=(READ, READ),
        return_effect=RETURN_ALIAS,
        return_alias_parameter=0,
        return_alias_shape=ALIAS_INTERIOR,
    ),
    "strtok": function(
        CHAR_PTR,
        CHAR_PTR,
        CONST_CHAR_PTR,
        effects=(MUTATE, READ),
        return_effect=RETURN_OPAQUE,
    ),
    "memset": _destination(VOID_PTR, VOID_PTR, INT, SIZE, effects=(MUTATE, VALUE, VALUE)),
    "strerror": function(CHAR_PTR, INT, return_effect=RETURN_INDEPENDENT),
    "strlen": function(SIZE, CONST_CHAR_PTR, effects=(READ,)),
    "strdup": function(
        CHAR_PTR,
        CONST_CHAR_PTR,
        effects=(READ,),
        return_effect=RETURN_FRESH,
        return_deallocator=DEALLOC_FREE,
    ),
    "strnlen": function(SIZE, CONST_CHAR_PTR, SIZE, effects=(READ, VALUE)),
}

__all__ = ["HOSTED_STRING_FUNCTIONS", "HOSTED_STRING_NAMES"]
