"""Owned names and exact representable ABI specs from ``stdio.h``."""

from .hosted_abi_model import (
    ALIAS_EXACT,
    CHAR_PTR,
    CONST_CHAR_PTR,
    CONST_VOID_PTR,
    CONSUME,
    FILE_PTR,
    INT,
    LONG,
    MUTATE,
    READ,
    RETURN_ALIAS,
    RETURN_INDEPENDENT,
    SIZE,
    VALUE,
    VOID,
    VOID_PTR,
    HostedFunction,
    abi_type,
    function,
)

HOSTED_STDIO_NAMES = frozenset(
    [
        "remove",
        "rename",
        "tmpfile",
        "tmpnam",
        "fclose",
        "fflush",
        "fopen",
        "freopen",
        "setbuf",
        "setvbuf",
        "fprintf",
        "fscanf",
        "printf",
        "scanf",
        "snprintf",
        "sprintf",
        "sscanf",
        "vfprintf",
        "vfscanf",
        "vprintf",
        "vscanf",
        "vsnprintf",
        "vsprintf",
        "vsscanf",
        "fgetc",
        "fgets",
        "fputc",
        "fputs",
        "getc",
        "getchar",
        "putc",
        "putchar",
        "puts",
        "ungetc",
        "fread",
        "fwrite",
        "fgetpos",
        "fseek",
        "fsetpos",
        "ftell",
        "rewind",
        "clearerr",
        "feof",
        "ferror",
        "perror",
        "popen",
        "pclose",
        "fileno",
        "flockfile",
        "funlockfile",
    ]
)

HOSTED_STDIO_FUNCTIONS: dict[str, HostedFunction] = {
    "remove": function(INT, CONST_CHAR_PTR, effects=(READ,)),
    "rename": function(INT, CONST_CHAR_PTR, CONST_CHAR_PTR, effects=(READ, READ)),
    "tmpfile": function(
        FILE_PTR,
        return_effect=RETURN_INDEPENDENT,
        return_deallocator="fclose",
    ),
    "fclose": function(
        INT,
        FILE_PTR,
        effects=(CONSUME,),
        raw_lifetime=True,
        consume_deallocator="fclose",
    ),
    "fflush": function(INT, FILE_PTR, effects=(MUTATE,)),
    "fopen": function(
        FILE_PTR,
        CONST_CHAR_PTR,
        CONST_CHAR_PTR,
        effects=(READ, READ),
        return_effect=RETURN_INDEPENDENT,
        return_deallocator="fclose",
    ),
    "freopen": function(
        FILE_PTR,
        CONST_CHAR_PTR,
        CONST_CHAR_PTR,
        FILE_PTR,
        effects=(READ, READ, MUTATE),
        return_effect=RETURN_ALIAS,
        return_alias_parameter=2,
        return_alias_shape=ALIAS_EXACT,
    ),
    "printf": function(INT, CONST_CHAR_PTR, effects=(READ,), variadic=True),
    "fprintf": function(INT, FILE_PTR, CONST_CHAR_PTR, effects=(MUTATE, READ), variadic=True),
    "sprintf": function(INT, CHAR_PTR, CONST_CHAR_PTR, effects=(MUTATE, READ), variadic=True),
    "snprintf": function(
        INT,
        CHAR_PTR,
        SIZE,
        CONST_CHAR_PTR,
        effects=(MUTATE, VALUE, READ),
        variadic=True,
    ),
    "fgetc": function(INT, FILE_PTR, effects=(MUTATE,)),
    "fgets": function(
        CHAR_PTR,
        CHAR_PTR,
        INT,
        FILE_PTR,
        effects=(MUTATE, VALUE, MUTATE),
        return_effect=RETURN_ALIAS,
        return_alias_parameter=0,
        return_alias_shape=ALIAS_EXACT,
    ),
    "fputc": function(INT, INT, FILE_PTR, effects=(VALUE, MUTATE)),
    "fputs": function(INT, CONST_CHAR_PTR, FILE_PTR, effects=(READ, MUTATE)),
    "getc": function(INT, FILE_PTR, effects=(MUTATE,)),
    "getchar": function(INT),
    "putc": function(INT, INT, FILE_PTR, effects=(VALUE, MUTATE)),
    "putchar": function(INT, INT),
    "puts": function(INT, CONST_CHAR_PTR, effects=(READ,)),
    "ungetc": function(INT, INT, FILE_PTR, effects=(VALUE, MUTATE)),
    "fread": function(SIZE, VOID_PTR, SIZE, SIZE, FILE_PTR, effects=(MUTATE, VALUE, VALUE, MUTATE)),
    "fwrite": function(
        SIZE,
        CONST_VOID_PTR,
        SIZE,
        SIZE,
        FILE_PTR,
        effects=(READ, VALUE, VALUE, MUTATE),
    ),
    "fseek": function(INT, FILE_PTR, LONG, INT, effects=(MUTATE, VALUE, VALUE)),
    "ftell": function(LONG, FILE_PTR, effects=(READ,)),
    "rewind": function(VOID, FILE_PTR, effects=(MUTATE,)),
    "clearerr": function(VOID, FILE_PTR, effects=(MUTATE,)),
    "feof": function(
        INT,
        FILE_PTR,
        effects=(READ,),
        semantic_result=abi_type("bool"),
    ),
    "ferror": function(
        INT,
        FILE_PTR,
        effects=(READ,),
        semantic_result=abi_type("bool"),
    ),
    "perror": function(VOID, CONST_CHAR_PTR, effects=(READ,)),
    "popen": function(
        FILE_PTR,
        CONST_CHAR_PTR,
        CONST_CHAR_PTR,
        effects=(READ, READ),
        return_effect=RETURN_INDEPENDENT,
        return_deallocator="pclose",
    ),
    "pclose": function(
        INT,
        FILE_PTR,
        effects=(CONSUME,),
        raw_lifetime=True,
        consume_deallocator="pclose",
    ),
    "fileno": function(INT, FILE_PTR, effects=(READ,)),
    "flockfile": function(VOID, FILE_PTR, effects=(MUTATE,)),
    "funlockfile": function(VOID, FILE_PTR, effects=(MUTATE,)),
}

__all__ = ["HOSTED_STDIO_FUNCTIONS", "HOSTED_STDIO_NAMES"]
