"""Compiler-owned names supplied as macros or constants by hosted headers."""

_LIMITS = {
    "CHAR_BIT",
    "SCHAR_MIN",
    "SCHAR_MAX",
    "UCHAR_MAX",
    "CHAR_MIN",
    "CHAR_MAX",
    "MB_LEN_MAX",
    "SHRT_MIN",
    "SHRT_MAX",
    "USHRT_MAX",
    "INT_MIN",
    "INT_MAX",
    "UINT_MAX",
    "LONG_MIN",
    "LONG_MAX",
    "ULONG_MAX",
    "LLONG_MIN",
    "LLONG_MAX",
    "ULLONG_MAX",
}
_STDIO = {
    "EOF",
    "BUFSIZ",
    "FILENAME_MAX",
    "FOPEN_MAX",
    "L_tmpnam",
    "SEEK_CUR",
    "SEEK_END",
    "SEEK_SET",
    "TMP_MAX",
    "_IOFBF",
    "_IOLBF",
    "_IONBF",
    "stdin",
    "stdout",
    "stderr",
}
_STDLIB = {"EXIT_FAILURE", "EXIT_SUCCESS", "RAND_MAX", "MB_CUR_MAX"}
_FLOAT = {
    "FLT_RADIX",
    "FLT_ROUNDS",
    "FLT_EVAL_METHOD",
    "DECIMAL_DIG",
    *(
        f"{family}_{suffix}"
        for family in ("FLT", "DBL", "LDBL")
        for suffix in (
            "DECIMAL_DIG",
            "MANT_DIG",
            "DIG",
            "MIN_EXP",
            "MIN_10_EXP",
            "MAX_EXP",
            "MAX_10_EXP",
            "MAX",
            "EPSILON",
            "MIN",
            "TRUE_MIN",
            "HAS_SUBNORM",
        )
    ),
}
_STDINT = {
    *(f"INT{width}_{bound}" for width in (8, 16, 32, 64) for bound in ("MIN", "MAX")),
    *(f"UINT{width}_MAX" for width in (8, 16, 32, 64)),
    *(
        f"INT_{family}{width}_{bound}"
        for family in ("LEAST", "FAST")
        for width in (8, 16, 32, 64)
        for bound in ("MIN", "MAX")
    ),
    *(f"UINT_{family}{width}_MAX" for family in ("LEAST", "FAST") for width in (8, 16, 32, 64)),
    "INTPTR_MIN",
    "INTPTR_MAX",
    "UINTPTR_MAX",
    "INTMAX_MIN",
    "INTMAX_MAX",
    "UINTMAX_MAX",
    "PTRDIFF_MIN",
    "PTRDIFF_MAX",
    "SIG_ATOMIC_MIN",
    "SIG_ATOMIC_MAX",
    "SIZE_MAX",
    "WCHAR_MIN",
    "WCHAR_MAX",
    "WINT_MIN",
    "WINT_MAX",
    "INT8_C",
    "INT16_C",
    "INT32_C",
    "INT64_C",
    "UINT8_C",
    "UINT16_C",
    "UINT32_C",
    "UINT64_C",
    "INTMAX_C",
    "UINTMAX_C",
}
_MATH = {
    "HUGE_VAL",
    "HUGE_VALF",
    "HUGE_VALL",
    "INFINITY",
    "NAN",
    "FP_INFINITE",
    "FP_NAN",
    "FP_NORMAL",
    "FP_SUBNORMAL",
    "FP_ZERO",
    "FP_FAST_FMA",
    "FP_FAST_FMAF",
    "FP_FAST_FMAL",
    "MATH_ERRNO",
    "MATH_ERREXCEPT",
    "math_errhandling",
    "fpclassify",
    "isfinite",
    "isinf",
    "isnan",
    "isnormal",
    "signbit",
    "isgreater",
    "isgreaterequal",
    "isless",
    "islessequal",
    "islessgreater",
    "isunordered",
}
_ATOMIC = {
    "ATOMIC_BOOL_LOCK_FREE",
    "ATOMIC_CHAR_LOCK_FREE",
    "ATOMIC_CHAR16_T_LOCK_FREE",
    "ATOMIC_CHAR32_T_LOCK_FREE",
    "ATOMIC_WCHAR_T_LOCK_FREE",
    "ATOMIC_SHORT_LOCK_FREE",
    "ATOMIC_INT_LOCK_FREE",
    "ATOMIC_LONG_LOCK_FREE",
    "ATOMIC_LLONG_LOCK_FREE",
    "ATOMIC_POINTER_LOCK_FREE",
    "ATOMIC_FLAG_INIT",
    "atomic_init",
    "atomic_is_lock_free",
    "atomic_store",
    "atomic_store_explicit",
    "atomic_load",
    "atomic_load_explicit",
    "atomic_exchange",
    "atomic_exchange_explicit",
    "atomic_compare_exchange_strong",
    "atomic_compare_exchange_strong_explicit",
    "atomic_compare_exchange_weak",
    "atomic_compare_exchange_weak_explicit",
    "atomic_fetch_add",
    "atomic_fetch_add_explicit",
    "atomic_fetch_sub",
    "atomic_fetch_sub_explicit",
    "atomic_fetch_or",
    "atomic_fetch_or_explicit",
    "atomic_fetch_xor",
    "atomic_fetch_xor_explicit",
    "atomic_fetch_and",
    "atomic_fetch_and_explicit",
    "atomic_flag_test_and_set",
    "atomic_flag_test_and_set_explicit",
    "atomic_flag_clear",
    "atomic_flag_clear_explicit",
    "atomic_thread_fence",
    "atomic_signal_fence",
    "kill_dependency",
    "memory_order_relaxed",
    "memory_order_consume",
    "memory_order_acquire",
    "memory_order_release",
    "memory_order_acq_rel",
    "memory_order_seq_cst",
}
_PTHREAD = {
    "PTHREAD_MUTEX_INITIALIZER",
    "PTHREAD_COND_INITIALIZER",
    "PTHREAD_ONCE_INIT",
    "PTHREAD_CANCELED",
}

HOSTED_MACROS = frozenset(
    {
        "_DEFAULT_SOURCE",
        "_DARWIN_C_SOURCE",
        "assert",
        "static_assert",
        "setjmp",
        "NULL",
        "va_start",
        "va_arg",
        "va_copy",
        "va_end",
        "offsetof",
        "errno",
        "true",
        "false",
        "__bool_true_false_are_defined",
        *_LIMITS,
        *_STDIO,
        *_STDLIB,
        *_FLOAT,
        *_STDINT,
        *_MATH,
        *_ATOMIC,
        *_PTHREAD,
    }
)

__all__ = ["HOSTED_MACROS"]
